var HORIZONTAL_ICON_SIZE = 16;
var ICON_HEIGHT_FACTOR = 0.75;
var VERTICAL_ICON_HEIGHT_FACTOR = 0.75;
var MAX_TEXT_LENGTH = 1000;
var FLASH_INTERVAL = 500;
var WINDOW_PREVIEW_WIDTH = 200;
var WINDOW_PREVIEW_HEIGHT = 150;

/* exported HORIZONTAL_ICON_SIZE,
            ICON_HEIGHT_FACTOR,
            VERTICAL_ICON_HEIGHT_FACTOR,
            MAX_TEXT_LENGTH,
            FLASH_INTERVAL,
            WINDOW_PREVIEW_WIDTH,
            WINDOW_PREVIEW_HEIGHT,
 */
