#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Knowledge Base documentation build configuration file, created by
# sphinx-quickstart on Mon Nov 13 12:08:10 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# auto generated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys

root_folder = os.path.realpath(os.path.abspath(os.path.join(
    os.path.normpath(os.path.join(os.path.dirname(__file__), *([".."] * 2))))))

local_modules_paths = [
    os.path.join(root_folder, "__app__"),
]

for p in local_modules_paths:
    sys.path.insert(0, p)

extensions_path = os.path.abspath(".")
sys.path.insert(0, extensions_path)

# I couldn't directly import this data from the extension code itself (freaking python's relative
# imports nonsense!!!), so I import it here and pass the data to the extension as an option
# dictionary. Moving on!!!
from python_modules.cli import docopt_doc as cinnamontools_docopt_doc

# ##############################################################################
# ########################### General configuration ############################
# ##############################################################################

# If your documentation needs a minimal Sphinx version, state it here.
#
needs_sphinx = "1.6"

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
source_suffix = [".rst", ".txt"]

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "Cinnamon Tools"
copyright = "2016-2018, Odyseus"
author = "Odyseus"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = ""
# The full version, including alpha/beta/rc tags.
release = ""

# The language for content auto generated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = []

# ##############################################################################
# ########################### Options for HTML output ##########################
# ##############################################################################

html_theme = "pydoctheme"

html_theme_path = ["."]

html_theme_options = {
    "collapsiblesidebar": False
}

html_output_encoding = "utf-8"

html_favicon = "images/cinnamon-logo.svg"

html_logo = "images/cinnamon-logo.png"

html_experimental_html5_writer = True

html_add_permalinks = "¶"

html_copy_source = True

html_show_sourcelink = True

html_show_copyright = True

html_show_sphinx = True

html_compact_lists = True

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

# ##############################################################################
# ########################## Extensions settings ###############################
# ##############################################################################

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.intersphinx",
    "sphinx.ext.coverage",
    "sphinx.ext.viewcode",
    "sphinx.ext.githubpages",
    # My Sphinx extensions
    "extensions.docopt_doc_literalinclude"
]

# sphinx.ext.napoleon settings
napoleon_google_docstring = False
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = False
napoleon_include_private_with_doc = True
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = True
napoleon_use_admonition_for_notes = True
napoleon_use_admonition_for_references = True
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True


# sphinx.ext.coverage.
coverage_ignore_modules = ["common_modules.docopt", "common_modules.pyperclip"]

# extensions.docopt_doc_literalinclude.
docopt_doc_literalinclude_docstrings = {
    "cinnamontools": cinnamontools_docopt_doc,
}

# ##############################################################################
# ########################## SMACK SOME FREAKING SENCE #########################
# ##############################################################################

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {
    "python": ("https://docs.python.org/3.5", "python.3.5.objects.inv")
}

# Python's docs don't change every week.
intersphinx_cache_limit = 90  # days


# include __init__ docstrings in class docstrings
autoclass_content = "both"

# Group method docstrings in sphinx
autodoc_member_order = "bysource"

# Just to know how to do this.
# I don't need custom JavaScript yet.
# I use a custom theme, so I made all CSS changes in there.
# def setup(app):
#     # In case that I need in the future to add CSS.
#     app.add_stylesheet("css/custom.css")
#     # In case that I need in the future to add JavaScript.
#     app.add_javascript("js/custom.js")
