let Constants;

// Mark for deletion on EOL. Cinnamon 3.6.x+
if (typeof require === "function") {
    Constants = require("./constants.js");
} else {
    Constants = imports.ui.extensionSystem.extensions["{{UUID}}"].constants;
}

const {
    _,
    ELLIPSIS
} = Constants;

var NameThatColor = {
    /* Name that Color JavaScript library created by Chirag Mehta.
     * http://chir.ag/projects/ntc
     *
     * Modified by Colblindor to also return color shades.
     * http://www.color-blindness.com/color-name-hue-tool/js/ntc.js
     *
     * Modified by Odyseus:
     * - Made strict mode compliant.
     * - Return an object instead of an array when naming a color.
     * - Use of inverse while loops for faster iterations.
     * - Added localization support.
     *
     * All the functions, code, lists etc. have been written specifically
     * for the Name that Color JavaScript library by Chirag Mehta unless
     * otherwise specified.
     *
     * This library is released under the: Creative Commons License:
     * Attribution 2.5 http://creativecommons.org/licenses/by/2.5/
     *
     * Sample Usage:
     *
     *     let n_match  = ntc.name("#6195ED");
     *     // This is the color value of the closest matching color in hexadecimal notation.
     *     let n_hex        = n_match.hex;
     *     // This is the color value of the closest matching color in RGB notation.
     *     let n_rgb        = n_match.rgb;
     *     // This is the text string for the name of the match.
     *     let n_name       = n_match.name;
     *     // This is the RGB value of the closest hue matching color.
     *     let n_hue_hex       = n_match.hueHex;
     *     // This is the text string for the name of the hue match.
     *     let n_hue_name       = n_match.hueName;
     *     // True if exact color match, False if close-match.
     *     let n_exactmatch = n_match.exact_match;
     *
     *     global.log(n_match.toSource());
     */
    init: function() {
        let color,
            rgb,
            hsl;
        let i = this.names.length;
        while (i--) {
            color = "#" + this.names[i][0];
            rgb = this.rgb(color);
            hsl = this.hsl(color);
            this.names[i].push(rgb[0], rgb[1], rgb[2], hsl[0], hsl[1], hsl[2]);
        }
    },

    name: function(color) {
        color = color.toUpperCase();

        /* NOTE: All these checks are suppressed because in my use case the input
         * color will always be in the format #000000.
         */
        // if (color.length < 3 || color.length > 7) {
        //     return {
        //         input: color,
        //         name: _("Invalid Color"),
        //         hex: ELLIPSIS,
        //         rgb: ELLIPSIS,
        //         hueName: _("Invalid Color"),
        //         hueHex: ELLIPSIS,
        //         exact_match: false
        //     };
        // }

        // if (color.length % 3 === 0) {
        //     color = "#" + color;
        // }

        // if (color.length === 4) {
        //     color = "#" + color.substr(1, 1) + color.substr(1, 1) +
        //         color.substr(2, 1) + color.substr(2, 1) +
        //         color.substr(3, 1) + color.substr(3, 1);
        // }

        let rgb = this.rgb(color);
        let r = rgb[0],
            g = rgb[1],
            b = rgb[2];
        let hsl = this.hsl(color);
        let h = hsl[0],
            s = hsl[1],
            l = hsl[2];
        let ndf1 = 0;
        let ndf2 = 0;
        let ndf = 0;
        let cl = -1,
            df = -1;

        let i = this.names.length;
        while (i--) {
            if (color === "#" + this.names[i][0]) {
                return {
                    input: color,
                    name: this.names[i][1],
                    hex: "#" + this.names[i][0],
                    rgb: "rgb(%d, %d, %d)".format(this.names[i][3],
                        this.names[i][4], this.names[i][5]),
                    hueName: this.names[i][2],
                    hueHex: this.shadergb(this.names[i][2]),
                    exact_match: true
                };
            }

            ndf1 = Math.pow(r - this.names[i][3], 2) +
                Math.pow(g - this.names[i][4], 2) +
                Math.pow(b - this.names[i][5], 2);
            ndf2 = Math.abs(Math.pow(h - this.names[i][6], 2)) +
                Math.pow(s - this.names[i][7], 2) +
                Math.abs(Math.pow(l - this.names[i][8], 2));
            ndf = ndf1 + ndf2 * 2;
            if (df < 0 || df > ndf) {
                df = ndf;
                cl = i;
            }
        }

        return (cl < 0 ? {
            input: color,
            name: _("Invalid Color"),
            hex: ELLIPSIS,
            rgb: ELLIPSIS,
            hueName: _("Invalid Color"),
            hueHex: ELLIPSIS,
            exact_match: false
        } : {
            input: color,
            name: this.names[cl][1],
            hex: "#" + this.names[cl][0],
            rgb: "rgb(%d, %d, %d)".format(this.names[cl][3],
                this.names[cl][4], this.names[cl][5]),
            hueName: this.names[cl][2],
            hueHex: this.shadergb(this.names[cl][2]),
            exact_match: false
        });
    },

    // Adopted from: Farbtastic 1.2.
    // http://acko.net/dev/farbtastic
    hsl: function(color) {
        let rgb = [
            parseInt("0x" + color.substring(1, 3), 16) / 255,
            parseInt("0x" + color.substring(3, 5), 16) / 255,
            parseInt("0x" + color.substring(5, 7), 16) / 255
        ];
        let min,
            max,
            delta,
            h,
            s,
            l;
        let r = rgb[0],
            g = rgb[1],
            b = rgb[2];

        min = Math.min(r, Math.min(g, b));
        max = Math.max(r, Math.max(g, b));
        delta = max - min;
        l = (min + max) / 2;

        s = 0;
        if (l > 0 && l < 1) {
            s = delta / (l < 0.5 ? (2 * l) : (2 - 2 * l));
        }

        h = 0;
        if (delta > 0) {
            if (max === r && max != g) {
                h += (g - b) / delta;
            }
            if (max === g && max != b) {
                h += (2 + (b - r) / delta);
            }
            if (max === b && max != r) {
                h += (4 + (r - g) / delta);
            }
            h /= 6;
        }
        return [
            parseInt(h * 255, 10),
            parseInt(s * 255, 10),
            parseInt(l * 255, 10)
        ];
    },

    // Adopted from: Farbtastic 1.2.
    // http://acko.net/dev/farbtastic
    rgb: function(color) {
        return [
            parseInt("0x" + color.substring(1, 3), 16),
            parseInt("0x" + color.substring(3, 5), 16),
            parseInt("0x" + color.substring(5, 7), 16)
        ];
    },

    shadergb: function(shadename) {
        for (let i = 0; i < this.shades.length; i++) {
            if (shadename === this.shades[i][1]) {
                return "#" + this.shades[i][0];
            }
        }
        return "#000000";
    },

    shades: [
        ["FF0000", _("Red")],
        ["FFA500", _("Orange")],
        ["FFFF00", _("Yellow")],
        ["008000", _("Green")],
        ["0000FF", _("Blue")],
        ["EE82EE", _("Violet")],
        ["A52A2A", _("Brown")],
        ["000000", _("Black")],
        ["808080", _("Grey")],
        ["FFFFFF", _("White")]
    ],

    names: [
        ["35312C", _("Acadia"), _("Brown")],
        ["75AA94", _("Acapulco"), _("Green")],
        ["C0E8D5", _("Aero Blue"), _("Green")],
        ["745085", _("Affair"), _("Violet")],
        ["905E26", _("Afghan Tan"), _("Yellow")],
        ["5D8AA8", _("Air Force Blue"), _("Blue")],
        ["BEB29A", _("Akaroa"), _("Yellow")],
        ["F2F0E6", _("Alabaster"), _("Grey")],
        ["E1DACB", _("Albescent White"), _("Yellow")],
        ["954E2C", _("Alert Tan"), _("Orange")],
        ["F0F8FF", _("Alice Blue"), _("Blue")],
        ["E32636", _("Alizarin"), _("Red")],
        ["1F6A7D", _("Allports"), _("Blue")],
        ["EED9C4", _("Almond"), _("Yellow")],
        ["9A8678", _("Almond Frost"), _("Brown")],
        ["AD8A3B", _("Alpine"), _("Yellow")],
        ["CDC6C5", _("Alto"), _("Grey")],
        ["848789", _("Aluminium"), _("Grey")],
        ["E52B50", _("Amaranth"), _("Red")],
        ["387B54", _("Amazon"), _("Green")],
        ["FFBF00", _("Amber"), _("Yellow")],
        ["8A7D72", _("Americano"), _("Brown")],
        ["9966CC", _("Amethyst"), _("Violet")],
        ["95879C", _("Amethyst Smoke"), _("Violet")],
        ["F5E6EA", _("Amour"), _("Violet")],
        ["7D9D72", _("Amulet"), _("Green")],
        ["8CCEEA", _("Anakiwa"), _("Blue")],
        ["6C461F", _("Antique Brass"), _("Orange")],
        ["FAEBD7", _("Antique White"), _("White")],
        ["C68E3F", _("Anzac"), _("Yellow")],
        ["D3A95C", _("Apache"), _("Yellow")],
        ["66B348", _("Apple"), _("Green")],
        ["A95249", _("Apple Blossom"), _("Red")],
        ["DEEADC", _("Apple Green"), _("Green")],
        ["FBCEB1", _("Apricot"), _("Orange")],
        ["F7F0DB", _("Apricot White"), _("Yellow")],
        ["00FFFF", _("Aqua"), _("Blue")],
        ["D9DDD5", _("Aqua Haze"), _("Grey")],
        ["E8F3E8", _("Aqua Spring"), _("Green")],
        ["DBE4DC", _("Aqua Squeeze"), _("Grey")],
        ["7FFFD4", _("Aquamarine"), _("Blue")],
        ["274A5D", _("Arapawa"), _("Blue")],
        ["484A46", _("Armadillo"), _("Grey")],
        ["4B5320", _("Army green"), _("Green")],
        ["827A67", _("Arrowtown"), _("Yellow")],
        ["3B444B", _("Arsenic"), _("Grey")],
        ["BEBAA7", _("Ash"), _("Green")],
        ["7BA05B", _("Asparagus"), _("Green")],
        ["EDD5A6", _("Astra"), _("Yellow")],
        ["376F89", _("Astral"), _("Blue")],
        ["445172", _("Astronaut"), _("Blue")],
        ["214559", _("Astronaut Blue"), _("Blue")],
        ["DCDDDD", _("Athens Grey"), _("Grey")],
        ["D5CBB2", _("Aths Special"), _("Yellow")],
        ["9CD03B", _("Atlantis"), _("Green")],
        ["2B797A", _("Atoll"), _("Green")],
        ["3D4B52", _("Atomic"), _("Blue")],
        ["FF9966", _("Atomic Tangerine"), _("Orange")],
        ["9E6759", _("Au Chico"), _("Brown")],
        ["372528", _("Aubergine"), _("Brown")],
        ["712F2C", _("Auburn"), _("Brown")],
        ["EFF8AA", _("Australian Mint"), _("Green")],
        ["95986B", _("Avocado"), _("Green")],
        ["63775A", _("Axolotl"), _("Green")],
        ["F9C0C4", _("Azalea"), _("Red")],
        ["293432", _("Aztec"), _("Green")],
        ["F0FFFF", _("Azure"), _("Blue")],
        ["6FFFFF", _("Baby Blue"), _("Blue")],
        ["25597F", _("Bahama Blue"), _("Blue")],
        ["A9C01C", _("Bahia"), _("Green")],
        ["5C3317", _("Baker's Chocolate"), _("Brown")],
        ["849CA9", _("Bali Hai"), _("Blue")],
        ["3C3D3E", _("Baltic Sea"), _("Grey")],
        ["FBE7B2", _("Banana Mania"), _("Yellow")],
        ["878466", _("Bandicoot"), _("Green")],
        ["D2C61F", _("Barberry"), _("Green")],
        ["B6935C", _("Barley Corn"), _("Yellow")],
        ["F7E5B7", _("Barley White"), _("Yellow")],
        ["452E39", _("Barossa"), _("Violet")],
        ["2C2C32", _("Bastille"), _("Blue")],
        ["51574F", _("Battleship Grey"), _("Grey")],
        ["7BB18D", _("Bay Leaf"), _("Green")],
        ["353E64", _("Bay Of Many"), _("Blue")],
        ["8F7777", _("Bazaar"), _("Brown")],
        ["EBB9B3", _("Beauty Bush"), _("Red")],
        ["926F5B", _("Beaver"), _("Brown")],
        ["E9D7AB", _("Beeswax"), _("Yellow")],
        ["F5F5DC", _("Beige"), _("Brown")],
        ["86D2C1", _("Bermuda"), _("Green")],
        ["6F8C9F", _("Bermuda Grey"), _("Blue")],
        ["BCBFA8", _("Beryl Green"), _("Green")],
        ["F4EFE0", _("Bianca"), _("Yellow")],
        ["334046", _("Big Stone"), _("Blue")],
        ["3E8027", _("Bilbao"), _("Green")],
        ["AE99D2", _("Biloba Flower"), _("Violet")],
        ["3F3726", _("Birch"), _("Yellow")],
        ["D0C117", _("Bird Flower"), _("Green")],
        ["2F3C53", _("Biscay"), _("Blue")],
        ["486C7A", _("Bismark"), _("Blue")],
        ["B5AC94", _("Bison Hide"), _("Yellow")],
        ["FFE4C4", _("Bisque"), _("Brown")],
        ["3D2B1F", _("Bistre"), _("Brown")],
        ["88896C", _("Bitter"), _("Green")],
        ["D2DB32", _("Bitter Lemon"), _("Green")],
        ["FE6F5E", _("Bittersweet"), _("Orange")],
        ["E7D2C8", _("Bizarre"), _("Orange")],
        ["000000", _("Black"), _("Black")],
        ["232E26", _("Black Bean"), _("Green")],
        ["2C3227", _("Black Forest"), _("Green")],
        ["E0DED7", _("Black Haze"), _("Grey")],
        ["332C22", _("Black Magic"), _("Brown")],
        ["383740", _("Black Marlin"), _("Blue")],
        ["1E272C", _("Black Pearl"), _("Blue")],
        ["2C2D3C", _("Black Rock"), _("Blue")],
        ["532934", _("Black Rose"), _("Red")],
        ["24252B", _("Black Russian"), _("Grey")],
        ["E5E6DF", _("Black Squeeze"), _("Grey")],
        ["E5E4DB", _("Black White"), _("Grey")],
        ["43182F", _("Blackberry"), _("Violet")],
        ["2E183B", _("Blackcurrant"), _("Violet")],
        ["D9D0C1", _("Blanc"), _("Yellow")],
        ["FFEBCD", _("Blanched Almond"), _("Brown")],
        ["EBE1CE", _("Bleach White"), _("Yellow")],
        ["A3E3ED", _("Blizzard Blue"), _("Blue")],
        ["DFB1B6", _("Blossom"), _("Red")],
        ["0000FF", _("Blue"), _("Blue")],
        ["62777E", _("Blue Bayoux"), _("Blue")],
        ["9999CC", _("Blue Bell"), _("Blue")],
        ["E3D6E9", _("Blue Chalk"), _("Violet")],
        ["262B2F", _("Blue Charcoal"), _("Blue")],
        ["408F90", _("Blue Chill"), _("Green")],
        ["4B2D72", _("Blue Diamond"), _("Violet")],
        ["35514F", _("Blue Dianne"), _("Green")],
        ["4B3C8E", _("Blue Gem"), _("Violet")],
        ["BDBACE", _("Blue Haze"), _("Violet")],
        ["00626F", _("Blue Lagoon"), _("Green")],
        ["6A5BB1", _("Blue Marguerite"), _("Violet")],
        ["D8F0D2", _("Blue Romance"), _("Green")],
        ["78857A", _("Blue Smoke"), _("Green")],
        ["166461", _("Blue Stone"), _("Green")],
        ["8A2BE2", _("Blue Violet"), _("Violet")],
        ["1E3442", _("Blue Whale"), _("Blue")],
        ["3C4354", _("Blue Zodiac"), _("Blue")],
        ["305C71", _("Blumine"), _("Blue")],
        ["B55067", _("Blush"), _("Red")],
        ["2A2725", _("Bokara Grey"), _("Grey")],
        ["79443B", _("Bole"), _("Brown")],
        ["AEAEAD", _("Bombay"), _("Grey")],
        ["DFD7D2", _("Bon Jour"), _("Grey")],
        ["0095B6", _("Bondi Blue"), _("Blue")],
        ["DBC2AB", _("Bone"), _("Orange")],
        ["4C1C24", _("Bordeaux"), _("Red")],
        ["4C3D4E", _("Bossanova"), _("Violet")],
        ["438EAC", _("Boston Blue"), _("Blue")],
        ["92ACB4", _("Botticelli"), _("Blue")],
        ["254636", _("Bottle Green"), _("Green")],
        ["7C817C", _("Boulder"), _("Grey")],
        ["A78199", _("Bouquet"), _("Violet")],
        ["AF6C3E", _("Bourbon"), _("Orange")],
        ["5B3D27", _("Bracken"), _("Brown")],
        ["DCB68A", _("Brandy"), _("Orange")],
        ["C07C40", _("Brandy Punch"), _("Orange")],
        ["B6857A", _("Brandy Rose"), _("Red")],
        ["B5A642", _("Brass"), _("Yellow")],
        ["517B78", _("Breaker Bay"), _("Green")],
        ["C62D42", _("Brick Red"), _("Red")],
        ["F8EBDD", _("Bridal Heath"), _("Orange")],
        ["FAE6DF", _("Bridesmaid"), _("Orange")],
        ["66FF00", _("Bright Green"), _("Green")],
        ["57595D", _("Bright Grey"), _("Grey")],
        ["922A31", _("Bright Red"), _("Red")],
        ["ECBD2C", _("Bright Sun"), _("Yellow")],
        ["08E8DE", _("Bright Turquoise"), _("Blue")],
        ["FF55A3", _("Brilliant Rose"), _("Red")],
        ["FB607F", _("Brink Pink"), _("Red")],
        ["004225", _("British Racing Green"), _("Green")],
        ["A79781", _("Bronco"), _("Brown")],
        ["CD7F32", _("Bronze"), _("Brown")],
        ["584C25", _("Bronze Olive"), _("Yellow")],
        ["434C28", _("Bronzetone"), _("Yellow")],
        ["EECC24", _("Broom"), _("Yellow")],
        ["A52A2A", _("Brown"), _("Brown")],
        ["53331E", _("Brown Bramble"), _("Brown")],
        ["594537", _("Brown Derby"), _("Brown")],
        ["3C241B", _("Brown Pod"), _("Brown")],
        ["E6F2EA", _("Bubbles"), _("Green")],
        ["6E5150", _("Buccaneer"), _("Red")],
        ["A5A88F", _("Bud"), _("Green")],
        ["BC9B1B", _("Buddha Gold"), _("Yellow")],
        ["F0DC82", _("Buff"), _("Yellow")],
        ["482427", _("Bulgarian Rose"), _("Red")],
        ["75442B", _("Bull Shot"), _("Orange")],
        ["292C2F", _("Bunker"), _("Grey")],
        ["2B3449", _("Bunting"), _("Blue")],
        ["800020", _("Burgundy"), _("Red")],
        ["DEB887", _("Burly Wood"), _("Brown")],
        ["234537", _("Burnham"), _("Green")],
        ["D08363", _("Burning Sand"), _("Orange")],
        ["582124", _("Burnt Crimson"), _("Red")],
        ["FF7034", _("Burnt Orange"), _("Orange")],
        ["E97451", _("Burnt Sienna"), _("Brown")],
        ["8A3324", _("Burnt Umber"), _("Brown")],
        ["DA9429", _("Buttercup"), _("Yellow")],
        ["9D702E", _("Buttered Rum"), _("Yellow")],
        ["68578C", _("Butterfly Bush"), _("Violet")],
        ["F6E0A4", _("Buttermilk"), _("Yellow")],
        ["F1EBDA", _("Buttery White"), _("Yellow")],
        ["4A2E32", _("Cab Sav"), _("Red")],
        ["CD526C", _("Cabaret"), _("Red")],
        ["4C5544", _("Cabbage Pont"), _("Green")],
        ["5B6F55", _("Cactus"), _("Green")],
        ["5F9EA0", _("Cadet Blue"), _("Blue")],
        ["984961", _("Cadillac"), _("Red")],
        ["6A4928", _("Cafe Royale"), _("Brown")],
        ["D5B185", _("Calico"), _("Brown")],
        ["E98C3A", _("California"), _("Orange")],
        ["3D7188", _("Calypso"), _("Blue")],
        ["206937", _("Camarone"), _("Green")],
        ["803A4B", _("Camelot"), _("Red")],
        ["CCA483", _("Cameo"), _("Brown")],
        ["4F4D32", _("Camouflage"), _("Yellow")],
        ["78866B", _("Camouflage Green"), _("Green")],
        ["D08A9B", _("Can Can"), _("Red")],
        ["FFFF99", _("Canary"), _("Yellow")],
        ["8E5164", _("Cannon Pink"), _("Red")],
        ["4E5552", _("Cape Cod"), _("Grey")],
        ["FEE0A5", _("Cape Honey"), _("Yellow")],
        ["75482F", _("Cape Palliser"), _("Orange")],
        ["AFC182", _("Caper"), _("Green")],
        ["592720", _("Caput Mortuum"), _("Brown")],
        ["FFD59A", _("Caramel"), _("Yellow")],
        ["EBE5D5", _("Cararra"), _("Green")],
        ["1B3427", _("Cardin Green"), _("Green")],
        ["C41E3A", _("Cardinal"), _("Red")],
        ["C99AA0", _("Careys Pink"), _("Red")],
        ["00CC99", _("Caribbean Green"), _("Green")],
        ["E68095", _("Carissma"), _("Red")],
        ["F5F9CB", _("Carla"), _("Green")],
        ["960018", _("Carmine"), _("Red")],
        ["5B3A24", _("Carnaby Tan"), _("Brown")],
        ["FFA6C9", _("Carnation Pink"), _("Red")],
        ["F8DBE0", _("Carousel Pink"), _("Red")],
        ["ED9121", _("Carrot Orange"), _("Orange")],
        ["F0B253", _("Casablanca"), _("Yellow")],
        ["3F545A", _("Casal"), _("Blue")],
        ["8CA8A0", _("Cascade"), _("Green")],
        ["D1B399", _("Cashmere"), _("Brown")],
        ["AAB5B8", _("Casper"), _("Blue")],
        ["44232F", _("Castro"), _("Red")],
        ["273C5A", _("Catalina Blue"), _("Blue")],
        ["E0E4DC", _("Catskill White"), _("Grey")],
        ["E0B8B1", _("Cavern Pink"), _("Red")],
        ["9271A7", _("Ce Soir"), _("Violet")],
        ["463430", _("Cedar"), _("Brown")],
        ["ACE1AF", _("Celadon"), _("Green")],
        ["B4C04C", _("Celery"), _("Green")],
        ["D2D2C0", _("Celeste"), _("Green")],
        ["3A4E5F", _("Cello"), _("Blue")],
        ["2B3F36", _("Celtic"), _("Green")],
        ["857158", _("Cement"), _("Brown")],
        ["DE3163", _("Cerise"), _("Violet")],
        ["007BA7", _("Cerulean"), _("Blue")],
        ["2A52BE", _("Cerulean Blue"), _("Blue")],
        ["FDE9E0", _("Chablis"), _("Red")],
        ["5A6E41", _("Chalet Green"), _("Green")],
        ["DFC281", _("Chalky"), _("Yellow")],
        ["475877", _("Chambray"), _("Blue")],
        ["E8CD9A", _("Chamois"), _("Yellow")],
        ["EED9B6", _("Champagne"), _("Yellow")],
        ["EDB8C7", _("Chantilly"), _("Red")],
        ["394043", _("Charade"), _("Blue")],
        ["464646", _("Charcoal"), _("Grey")],
        ["F8EADF", _("Chardon"), _("Orange")],
        ["FFC878", _("Chardonnay"), _("Yellow")],
        ["A4DCE6", _("Charlotte"), _("Blue")],
        ["D0748B", _("Charm"), _("Red")],
        ["7FFF00", _("Chartreuse"), _("Green")],
        ["DFFF00", _("Chartreuse Yellow"), _("Yellow")],
        ["419F59", _("Chateau Green"), _("Green")],
        ["B3ABB6", _("Chatelle"), _("Violet")],
        ["2C5971", _("Chathams Blue"), _("Blue")],
        ["88A95B", _("Chelsea Cucumber"), _("Green")],
        ["95532F", _("Chelsea Gem"), _("Orange")],
        ["DEC371", _("Chenin"), _("Yellow")],
        ["F5CD82", _("Cherokee"), _("Yellow")],
        ["372D52", _("Cherry Pie"), _("Violet")],
        ["F5D7DC", _("Cherub"), _("Red")],
        ["B94E48", _("Chestnut"), _("Brown")],
        ["666FB4", _("Chetwode Blue"), _("Blue")],
        ["5B5D56", _("Chicago"), _("Grey")],
        ["F0F5BB", _("Chiffon"), _("Green")],
        ["D05E34", _("Chilean Fire"), _("Orange")],
        ["F9F7DE", _("Chilean Heath"), _("Green")],
        ["FBF3D3", _("China Ivory"), _("Green")],
        ["B8AD8A", _("Chino"), _("Yellow")],
        ["9DD3A8", _("Chinook"), _("Green")],
        ["D2691E", _("Chocolate"), _("Brown")],
        ["382161", _("Christalle"), _("Violet")],
        ["71A91D", _("Christi"), _("Green")],
        ["BF652E", _("Christine"), _("Orange")],
        ["CAC7B7", _("Chrome White"), _("Green")],
        ["7D4E38", _("Cigar"), _("Brown")],
        ["242A2E", _("Cinder"), _("Grey")],
        ["FBD7CC", _("Cinderella"), _("Red")],
        ["E34234", _("Cinnabar"), _("Red")],
        ["5D3B2E", _("Cioccolato"), _("Brown")],
        ["8E9A21", _("Citron"), _("Green")],
        ["9FB70A", _("Citrus"), _("Green")],
        ["D2B3A9", _("Clam Shell"), _("Orange")],
        ["6E2233", _("Claret"), _("Red")],
        ["F4C8DB", _("Classic Rose"), _("Violet")],
        ["897E59", _("Clay Creek"), _("Yellow")],
        ["DFEFEA", _("Clear Day"), _("Green")],
        ["463623", _("Clinker"), _("Brown")],
        ["C2BCB1", _("Cloud"), _("Yellow")],
        ["353E4F", _("Cloud Burst"), _("Blue")],
        ["B0A99F", _("Cloudy"), _("Brown")],
        ["47562F", _("Clover"), _("Green")],
        ["0047AB", _("Cobalt"), _("Blue")],
        ["4F3835", _("Cocoa Bean"), _("Red")],
        ["35281E", _("Cocoa Brown"), _("Brown")],
        ["E1DABB", _("Coconut Cream"), _("Green")],
        ["2D3032", _("Cod Grey"), _("Grey")],
        ["726751", _("Coffee"), _("Yellow")],
        ["362D26", _("Coffee Bean"), _("Brown")],
        ["9A463D", _("Cognac"), _("Red")],
        ["3C2F23", _("Cola"), _("Brown")],
        ["9D8ABF", _("Cold Purple"), _("Violet")],
        ["CAB5B2", _("Cold Turkey"), _("Red")],
        ["9BDDFF", _("Columbia Blue"), _("Blue")],
        ["636373", _("Comet"), _("Blue")],
        ["4C785C", _("Como"), _("Green")],
        ["A0B1AE", _("Conch"), _("Green")],
        ["827F79", _("Concord"), _("Grey")],
        ["D2D1CD", _("Concrete"), _("Grey")],
        ["DDCB46", _("Confetti"), _("Green")],
        ["654D49", _("Congo Brown"), _("Brown")],
        ["B1DD52", _("Conifer"), _("Green")],
        ["C16F68", _("Contessa"), _("Red")],
        ["DA8A67", _("Copper"), _("Red")],
        ["77422C", _("Copper Canyon"), _("Orange")],
        ["996666", _("Copper Rose"), _("Violet")],
        ["95524C", _("Copper Rust"), _("Red")],
        ["FF7F50", _("Coral"), _("Orange")],
        ["F5D0C9", _("Coral Candy"), _("Red")],
        ["FF4040", _("Coral Red"), _("Red")],
        ["AB6E67", _("Coral Tree"), _("Red")],
        ["404D49", _("Corduroy"), _("Green")],
        ["BBB58D", _("Coriander"), _("Green")],
        ["5A4C42", _("Cork"), _("Brown")],
        ["FBEC5D", _("Corn"), _("Yellow")],
        ["F8F3C4", _("Corn Field"), _("Green")],
        ["42426F", _("Corn Flower Blue"), _("Blue")],
        ["8D702A", _("Corn Harvest"), _("Yellow")],
        ["FFF8DC", _("Corn Silk"), _("Yellow")],
        ["93CCEA", _("Cornflower"), _("Blue")],
        ["6495ED", _("Cornflower Blue"), _("Blue")],
        ["E9BA81", _("Corvette"), _("Orange")],
        ["794D60", _("Cosmic"), _("Violet")],
        ["E1F8E7", _("Cosmic Latte"), _("White")],
        ["FCD5CF", _("Cosmos"), _("Red")],
        ["625D2A", _("Costa Del Sol"), _("Green")],
        ["FFB7D5", _("Cotton Candy"), _("Red")],
        ["BFBAAF", _("Cotton Seed"), _("Yellow")],
        ["1B4B35", _("County Green"), _("Green")],
        ["443736", _("Cowboy"), _("Brown")],
        ["87382F", _("Crab Apple"), _("Red")],
        ["A65648", _("Crail"), _("Red")],
        ["DB5079", _("Cranberry"), _("Red")],
        ["4D3E3C", _("Crater Brown"), _("Brown")],
        ["FFFDD0", _("Cream"), _("White")],
        ["FFE39B", _("Cream Brulee"), _("Yellow")],
        ["EEC051", _("Cream Can"), _("Yellow")],
        ["393227", _("Creole"), _("Brown")],
        ["77712B", _("Crete"), _("Green")],
        ["DC143C", _("Crimson"), _("Red")],
        ["706950", _("Crocodile"), _("Yellow")],
        ["763C33", _("Crown Of Thorns"), _("Red")],
        ["B4E2D5", _("Cruise"), _("Green")],
        ["165B31", _("Crusoe"), _("Green")],
        ["F38653", _("Crusta"), _("Orange")],
        ["784430", _("Cumin"), _("Orange")],
        ["F5F4C1", _("Cumulus"), _("Green")],
        ["F5B2C5", _("Cupid"), _("Red")],
        ["3D85B8", _("Curious Blue"), _("Blue")],
        ["5C8173", _("Cutty Sark"), _("Green")],
        ["0F4645", _("Cyprus"), _("Green")],
        ["EDD2A4", _("Dairy Cream"), _("Yellow")],
        ["5B3E90", _("Daisy Bush"), _("Violet")],
        ["664A2D", _("Dallas"), _("Brown")],
        ["FED85D", _("Dandelion"), _("Yellow")],
        ["5B89C0", _("Danube"), _("Blue")],
        ["00008B", _("Dark Blue"), _("Blue")],
        ["654321", _("Dark Brown"), _("Brown")],
        ["08457E", _("Dark Cerulean"), _("Blue")],
        ["986960", _("Dark Chestnut"), _("Red")],
        ["CD5B45", _("Dark Coral"), _("Orange")],
        ["008B8B", _("Dark Cyan"), _("Green")],
        ["B8860B", _("Dark Goldenrod"), _("Yellow")],
        ["A9A9A9", _("Dark Gray"), _("Grey")],
        ["013220", _("Dark Green"), _("Green")],
        ["4A766E", _("Dark Green Copper"), _("Green")],
        ["BDB76B", _("Dark Khaki"), _("Yellow")],
        ["8B008B", _("Dark Magenta"), _("Violet")],
        ["556B2F", _("Dark Olive Green"), _("Green")],
        ["FF8C00", _("Dark Orange"), _("Orange")],
        ["9932CC", _("Dark Orchid"), _("Violet")],
        ["03C03C", _("Dark Pastel Green"), _("Green")],
        ["E75480", _("Dark Pink"), _("Red")],
        ["871F78", _("Dark Purple"), _("Violet")],
        ["8B0000", _("Dark Red"), _("Red")],
        ["45362B", _("Dark Rum"), _("Brown")],
        ["E9967A", _("Dark Salmon"), _("Orange")],
        ["8FBC8F", _("Dark Sea Green"), _("Green")],
        ["465352", _("Dark Slate"), _("Green")],
        ["483D8B", _("Dark Slate Blue"), _("Blue")],
        ["2F4F4F", _("Dark Slate Grey"), _("Grey")],
        ["177245", _("Dark Spring Green"), _("Green")],
        ["97694F", _("Dark Tan"), _("Brown")],
        ["FFA812", _("Dark Tangerine"), _("Orange")],
        ["00CED1", _("Dark Turquoise"), _("Blue")],
        ["9400D3", _("Dark Violet"), _("Violet")],
        ["855E42", _("Dark Wood"), _("Brown")],
        ["788878", _("Davy's Grey"), _("Grey")],
        ["9F9D91", _("Dawn"), _("Green")],
        ["E6D6CD", _("Dawn Pink"), _("Orange")],
        ["85CA87", _("De York"), _("Green")],
        ["CCCF82", _("Deco"), _("Green")],
        ["E36F8A", _("Deep Blush"), _("Red")],
        ["51412D", _("Deep Bronze"), _("Brown")],
        ["DA3287", _("Deep Cerise"), _("Violet")],
        ["193925", _("Deep Fir"), _("Green")],
        ["343467", _("Deep Koamaru"), _("Violet")],
        ["9955BB", _("Deep Lilac"), _("Violet")],
        ["CC00CC", _("Deep Magenta"), _("Violet")],
        ["FF1493", _("Deep Pink"), _("Red")],
        ["167E65", _("Deep Sea"), _("Green")],
        ["00BFFF", _("Deep Sky Blue"), _("Blue")],
        ["19443C", _("Deep Teal"), _("Green")],
        ["B5998E", _("Del Rio"), _("Brown")],
        ["486531", _("Dell"), _("Green")],
        ["999B95", _("Delta"), _("Grey")],
        ["8272A4", _("Deluge"), _("Violet")],
        ["1560BD", _("Denim"), _("Blue")],
        ["F9E4C6", _("Derby"), _("Yellow")],
        ["A15F3B", _("Desert"), _("Orange")],
        ["EDC9AF", _("Desert Sand"), _("Brown")],
        ["EDE7E0", _("Desert Storm"), _("Grey")],
        ["E7F2E9", _("Dew"), _("Green")],
        ["322C2B", _("Diesel"), _("Grey")],
        ["696969", _("Dim Gray"), _("Grey")],
        ["607C47", _("Dingley"), _("Green")],
        ["892D4F", _("Disco"), _("Red")],
        ["CD8431", _("Dixie"), _("Yellow")],
        ["1E90FF", _("Dodger Blue"), _("Blue")],
        ["F5F171", _("Dolly"), _("Green")],
        ["6A6873", _("Dolphin"), _("Violet")],
        ["6C5B4C", _("Domino"), _("Brown")],
        ["5A4F51", _("Don Juan"), _("Brown")],
        ["816E5C", _("Donkey Brown"), _("Brown")],
        ["6E5F56", _("Dorado"), _("Brown")],
        ["E4CF99", _("Double Colonial White"), _("Yellow")],
        ["E9DCBE", _("Double Pearl Lusta"), _("Yellow")],
        ["D2C3A3", _("Double Spanish White"), _("Yellow")],
        ["777672", _("Dove Grey"), _("Grey")],
        ["6FD2BE", _("Downy"), _("Green")],
        ["FBEB9B", _("Drover"), _("Yellow")],
        ["514F4A", _("Dune"), _("Grey")],
        ["E5CAC0", _("Dust Storm"), _("Orange")],
        ["AC9B9B", _("Dusty Grey"), _("Grey")],
        ["F0DFBB", _("Dutch White"), _("Yellow")],
        ["B0AC94", _("Eagle"), _("Green")],
        ["B8A722", _("Earls Green"), _("Green")],
        ["FBF2DB", _("Early Dawn"), _("Yellow")],
        ["47526E", _("East Bay"), _("Blue")],
        ["AA8CBC", _("East Side"), _("Violet")],
        ["00879F", _("Eastern Blue"), _("Blue")],
        ["E6D8D4", _("Ebb"), _("Red")],
        ["313337", _("Ebony"), _("Grey")],
        ["323438", _("Ebony Clay"), _("Grey")],
        ["A4AFCD", _("Echo Blue"), _("Blue")],
        ["3F3939", _("Eclipse"), _("Grey")],
        ["C2B280", _("Ecru"), _("Brown")],
        ["D6D1C0", _("Ecru White"), _("Green")],
        ["C96138", _("Ecstasy"), _("Orange")],
        ["266255", _("Eden"), _("Green")],
        ["C1D8C5", _("Edgewater"), _("Green")],
        ["97A49A", _("Edward"), _("Green")],
        ["F9E4C5", _("Egg Sour"), _("Yellow")],
        ["990066", _("Eggplant"), _("Violet")],
        ["1034A6", _("Egyptian Blue"), _("Blue")],
        ["39392C", _("El Paso"), _("Green")],
        ["8F4E45", _("El Salva"), _("Red")],
        ["7DF9FF", _("Electric Blue"), _("Blue")],
        ["6600FF", _("Electric Indigo"), _("Violet")],
        ["CCFF00", _("Electric Lime"), _("Green")],
        ["BF00FF", _("Electric Purple"), _("Violet")],
        ["243640", _("Elephant"), _("Blue")],
        ["1B8A6B", _("Elf Green"), _("Green")],
        ["297B76", _("Elm"), _("Green")],
        ["50C878", _("Emerald"), _("Green")],
        ["6E3974", _("Eminence"), _("Violet")],
        ["50494A", _("Emperor"), _("Grey")],
        ["7C7173", _("Empress"), _("Grey")],
        ["29598B", _("Endeavour"), _("Blue")],
        ["F5D752", _("Energy Yellow"), _("Yellow")],
        ["274234", _("English Holly"), _("Green")],
        ["8BA58F", _("Envy"), _("Green")],
        ["DAB160", _("Equator"), _("Yellow")],
        ["4E312D", _("Espresso"), _("Red")],
        ["2D2F28", _("Eternity"), _("Green")],
        ["329760", _("Eucalyptus"), _("Green")],
        ["CDA59C", _("Eunry"), _("Red")],
        ["26604F", _("Evening Sea"), _("Green")],
        ["264334", _("Everglade"), _("Green")],
        ["F3E5DC", _("Fair Pink"), _("Orange")],
        ["6E5A5B", _("Falcon"), _("Brown")],
        ["C19A6B", _("Fallow"), _("Brown")],
        ["801818", _("Falu Red"), _("Red")],
        ["F2E6DD", _("Fantasy"), _("Orange")],
        ["625665", _("Fedora"), _("Violet")],
        ["A5D785", _("Feijoa"), _("Green")],
        ["4D5D53", _("Feldgrau"), _("Grey")],
        ["D19275", _("Feldspar"), _("Red")],
        ["63B76C", _("Fern"), _("Green")],
        ["4F7942", _("Fern Green"), _("Green")],
        ["876A68", _("Ferra"), _("Brown")],
        ["EACC4A", _("Festival"), _("Yellow")],
        ["DBE0D0", _("Feta"), _("Green")],
        ["B1592F", _("Fiery Orange"), _("Orange")],
        ["636F22", _("Fiji Green"), _("Green")],
        ["75785A", _("Finch"), _("Green")],
        ["61755B", _("Finlandia"), _("Green")],
        ["694554", _("Finn"), _("Violet")],
        ["4B5A62", _("Fiord"), _("Blue")],
        ["8F3F2A", _("Fire"), _("Orange")],
        ["B22222", _("Fire Brick"), _("Red")],
        ["E09842", _("Fire Bush"), _("Yellow")],
        ["CE1620", _("Fire Engine Red"), _("Red")],
        ["314643", _("Firefly"), _("Green")],
        ["BE5C48", _("Flame Pea"), _("Orange")],
        ["86282E", _("Flame Red"), _("Red")],
        ["EA8645", _("Flamenco"), _("Orange")],
        ["E1634F", _("Flamingo"), _("Orange")],
        ["EEDC82", _("Flax"), _("Yellow")],
        ["716E61", _("Flint"), _("Green")],
        ["7A2E4D", _("Flirt"), _("Red")],
        ["FFFAF0", _("Floral White"), _("White")],
        ["D0EAE8", _("Foam"), _("Green")],
        ["D5C7E8", _("Fog"), _("Violet")],
        ["A7A69D", _("Foggy Grey"), _("Grey")],
        ["228B22", _("Forest Green"), _("Green")],
        ["FDEFDB", _("Forget Me Not"), _("Yellow")],
        ["65ADB2", _("Fountain Blue"), _("Blue")],
        ["FFD7A0", _("Frangipani"), _("Yellow")],
        ["029D74", _("Free Speech Aquamarine"), _("Green")],
        ["4156C5", _("Free Speech Blue"), _("Blue")],
        ["09F911", _("Free Speech Green"), _("Green")],
        ["E35BD8", _("Free Speech Magenta"), _("Red")],
        ["C00000", _("Free Speech Red"), _("Red")],
        ["BFBDC1", _("French Grey"), _("Grey")],
        ["DEB7D9", _("French Lilac"), _("Violet")],
        ["A4D2E0", _("French Pass"), _("Blue")],
        ["F64A8A", _("French Rose"), _("Red")],
        ["86837A", _("Friar Grey"), _("Grey")],
        ["B4E1BB", _("Fringy Flower"), _("Green")],
        ["E56D75", _("Froly"), _("Red")],
        ["E1E4C5", _("Frost"), _("Green")],
        ["E2F2E4", _("Frosted Mint"), _("Green")],
        ["DBE5D2", _("Frostee"), _("Green")],
        ["4BA351", _("Fruit Salad"), _("Green")],
        ["C154C1", _("Fuchsia"), _("Violet")],
        ["FF77FF", _("Fuchsia Pink"), _("Red")],
        ["C2D62E", _("Fuego"), _("Green")],
        ["D19033", _("Fuel Yellow"), _("Yellow")],
        ["335083", _("Fun Blue"), _("Blue")],
        ["15633D", _("Fun Green"), _("Green")],
        ["3C3B3C", _("Fuscous Grey"), _("Grey")],
        ["C45655", _("Fuzzy Wuzzy Brown"), _("Brown")],
        ["2C4641", _("Gable Green"), _("Green")],
        ["DCDCDC", _("Gainsboro"), _("White")],
        ["DCD7D1", _("Gallery"), _("Grey")],
        ["D8A723", _("Galliano"), _("Yellow")],
        ["E49B0F", _("Gamboge"), _("Yellow")],
        ["C5832E", _("Geebung"), _("Yellow")],
        ["31796D", _("Genoa"), _("Green")],
        ["E77B75", _("Geraldine"), _("Red")],
        ["CBD0CF", _("Geyser"), _("Grey")],
        ["C0BFC7", _("Ghost"), _("Blue")],
        ["F8F8FF", _("Ghost White"), _("White")],
        ["564786", _("Gigas"), _("Violet")],
        ["B9AD61", _("Gimblet"), _("Green")],
        ["D9DFCD", _("Gin"), _("Green")],
        ["F8EACA", _("Gin Fizz"), _("Yellow")],
        ["EBD4AE", _("Givry"), _("Yellow")],
        ["78B1BF", _("Glacier"), _("Blue")],
        ["5F8151", _("Glade Green"), _("Green")],
        ["786E4C", _("Go Ben"), _("Yellow")],
        ["34533D", _("Goblin"), _("Green")],
        ["FFD700", _("Gold"), _("Yellow")],
        ["D56C30", _("Gold Drop"), _("Orange")],
        ["E2B227", _("Gold Tips"), _("Yellow")],
        ["CA8136", _("Golden Bell"), _("Orange")],
        ["996515", _("Golden Brown"), _("Brown")],
        ["F1CC2B", _("Golden Dream"), _("Yellow")],
        ["EBDE31", _("Golden Fizz"), _("Green")],
        ["F9D77E", _("Golden Glow"), _("Yellow")],
        ["FCC200", _("Golden Poppy"), _("Yellow")],
        ["EACE6A", _("Golden Sand"), _("Yellow")],
        ["FFC152", _("Golden Tainoi"), _("Yellow")],
        ["FFDF00", _("Golden Yellow"), _("Yellow")],
        ["DBDB70", _("Goldenrod"), _("Yellow")],
        ["373332", _("Gondola"), _("Grey")],
        ["29332B", _("Gordons Green"), _("Green")],
        ["FDE336", _("Gorse"), _("Green")],
        ["399F86", _("Gossamer"), _("Green")],
        ["9FD385", _("Gossip"), _("Green")],
        ["698890", _("Gothic"), _("Blue")],
        ["51559B", _("Governor Bay"), _("Blue")],
        ["CAB8A2", _("Grain Brown"), _("Yellow")],
        ["FFCD73", _("Grandis"), _("Yellow")],
        ["8B8265", _("Granite Green"), _("Yellow")],
        ["C5E7CD", _("Granny Apple"), _("Green")],
        ["7B948C", _("Granny Smith"), _("Green")],
        ["9DE093", _("Granny Smith Apple"), _("Green")],
        ["413D4B", _("Grape"), _("Violet")],
        ["383428", _("Graphite"), _("Yellow")],
        ["4A4B46", _("Gravel"), _("Grey")],
        ["008000", _("Green"), _("Green")],
        ["3E6334", _("Green House"), _("Green")],
        ["393D2A", _("Green Kelp"), _("Green")],
        ["526B2D", _("Green Leaf"), _("Green")],
        ["BFC298", _("Green Mist"), _("Green")],
        ["266242", _("Green Pea"), _("Green")],
        ["9CA664", _("Green Smoke"), _("Green")],
        ["A9AF99", _("Green Spring"), _("Green")],
        ["23414E", _("Green Vogue"), _("Blue")],
        ["2C2D24", _("Green Waterloo"), _("Green")],
        ["DEDDCB", _("Green White"), _("Green")],
        ["ADFF2F", _("Green Yellow"), _("Green")],
        ["C14D36", _("Grenadier"), _("Orange")],
        ["808080", _("Grey"), _("Grey")],
        ["9FA3A7", _("Grey Chateau"), _("Grey")],
        ["BDBAAE", _("Grey Nickel"), _("Green")],
        ["D1D3CC", _("Grey Nurse"), _("Grey")],
        ["A19A7F", _("Grey Olive"), _("Yellow")],
        ["9391A0", _("Grey Suit"), _("Blue")],
        ["465945", _("Grey-Asparagus"), _("Green")],
        ["952E31", _("Guardsman Red"), _("Red")],
        ["343F5C", _("Gulf Blue"), _("Blue")],
        ["74B2A8", _("Gulf Stream"), _("Green")],
        ["A4ADB0", _("Gull Grey"), _("Grey")],
        ["ACC9B2", _("Gum Leaf"), _("Green")],
        ["718F8A", _("Gumbo"), _("Green")],
        ["484753", _("Gun Powder"), _("Violet")],
        ["2C3539", _("Gunmetal"), _("Blue")],
        ["7A7C76", _("Gunsmoke"), _("Grey")],
        ["989171", _("Gurkha"), _("Green")],
        ["9E8022", _("Hacienda"), _("Yellow")],
        ["633528", _("Hairy Heath"), _("Brown")],
        ["2C2A35", _("Haiti"), _("Violet")],
        ["EDE7C8", _("Half And Half"), _("Green")],
        ["558F93", _("Half Baked"), _("Blue")],
        ["F2E5BF", _("Half Colonial White"), _("Yellow")],
        ["FBF0D6", _("Half Dutch White"), _("Yellow")],
        ["F1EAD7", _("Half Pearl Lusta"), _("Yellow")],
        ["E6DBC7", _("Half Spanish White"), _("Yellow")],
        ["E8D4A2", _("Hampton"), _("Yellow")],
        ["5218FA", _("Han Purple"), _("Violet")],
        ["3FFF00", _("Harlequin"), _("Green")],
        ["C93413", _("Harley Davidson Orange"), _("Orange")],
        ["CBCEC0", _("Harp"), _("Green")],
        ["EAB76A", _("Harvest Gold"), _("Yellow")],
        ["3B2B2C", _("Havana"), _("Brown")],
        ["5784C1", _("Havelock Blue"), _("Blue")],
        ["99522B", _("Hawaiian Tan"), _("Orange")],
        ["D2DAED", _("Hawkes Blue"), _("Blue")],
        ["4F2A2C", _("Heath"), _("Red")],
        ["AEBBC1", _("Heather"), _("Blue")],
        ["948C7E", _("Heathered Grey"), _("Brown")],
        ["46473E", _("Heavy Metal"), _("Grey")],
        ["DF73FF", _("Heliotrope"), _("Violet")],
        ["69684B", _("Hemlock"), _("Yellow")],
        ["987D73", _("Hemp"), _("Brown")],
        ["928C3C", _("Highball"), _("Green")],
        ["7A9461", _("Highland"), _("Green")],
        ["A7A07E", _("Hillary"), _("Green")],
        ["736330", _("Himalaya"), _("Yellow")],
        ["DFF1D6", _("Hint Of Green"), _("Green")],
        ["F5EFEB", _("Hint Of Red"), _("Grey")],
        ["F6F5D7", _("Hint Of Yellow"), _("Green")],
        ["49889A", _("Hippie Blue"), _("Blue")],
        ["608A5A", _("Hippie Green"), _("Green")],
        ["AB495C", _("Hippie Pink"), _("Red")],
        ["A1A9A8", _("Hit Grey"), _("Grey")],
        ["FDA470", _("Hit Pink"), _("Orange")],
        ["BB8E34", _("Hokey Pokey"), _("Yellow")],
        ["647D86", _("Hoki"), _("Blue")],
        ["25342B", _("Holly"), _("Green")],
        ["F400A1", _("Hollywood Cerise"), _("Red")],
        ["5C3C6D", _("Honey Flower"), _("Violet")],
        ["F0FFF0", _("Honeydew"), _("White")],
        ["E8ED69", _("Honeysuckle"), _("Green")],
        ["CD6D93", _("Hopbush"), _("Violet")],
        ["648894", _("Horizon"), _("Blue")],
        ["6D562C", _("Horses Neck"), _("Yellow")],
        ["815B28", _("Hot Curry"), _("Yellow")],
        ["FF00CC", _("Hot Magenta"), _("Red")],
        ["FF69B4", _("Hot Pink"), _("Red")],
        ["4E2E53", _("Hot Purple"), _("Violet")],
        ["A7752C", _("Hot Toddy"), _("Yellow")],
        ["CEEFE4", _("Humming Bird"), _("Green")],
        ["355E3B", _("Hunter Green"), _("Green")],
        ["8B7E77", _("Hurricane"), _("Brown")],
        ["B2994B", _("Husk"), _("Yellow")],
        ["AFE3D6", _("Ice Cold"), _("Green")],
        ["CAE1D9", _("Iceberg"), _("Green")],
        ["EF95AE", _("Illusion"), _("Red")],
        ["B0E313", _("Inch Worm"), _("Green")],
        ["CD5C5C", _("Indian Red"), _("Red")],
        ["4F301F", _("Indian Tan"), _("Brown")],
        ["4B0082", _("Indigo"), _("Violet")],
        ["9C5B34", _("Indochine"), _("Orange")],
        ["002FA7", _("International Klein Blue"), _("Blue")],
        ["FF4F00", _("International Orange"), _("Orange")],
        ["03B4C8", _("Iris Blue"), _("Blue")],
        ["62422B", _("Irish Coffee"), _("Brown")],
        ["CBCDCD", _("Iron"), _("Grey")],
        ["706E66", _("Ironside Grey"), _("Grey")],
        ["865040", _("Ironstone"), _("Brown")],
        ["009900", _("Islamic Green"), _("Green")],
        ["F8EDDB", _("Island Spice"), _("Yellow")],
        ["FFFFF0", _("Ivory"), _("White")],
        ["3D325D", _("Jacarta"), _("Violet")],
        ["413628", _("Jacko Bean"), _("Brown")],
        ["3D3F7D", _("Jacksons Purple"), _("Violet")],
        ["00A86B", _("Jade"), _("Green")],
        ["E27945", _("Jaffa"), _("Orange")],
        ["CAE7E2", _("Jagged Ice"), _("Green")],
        ["3F2E4C", _("Jagger"), _("Violet")],
        ["29292F", _("Jaguar"), _("Blue")],
        ["674834", _("Jambalaya"), _("Brown")],
        ["2F7532", _("Japanese Laurel"), _("Green")],
        ["CE7259", _("Japonica"), _("Orange")],
        ["259797", _("Java"), _("Green")],
        ["5F2C2F", _("Jazz"), _("Red")],
        ["A50B5E", _("Jazzberry Jam"), _("Red")],
        ["44798E", _("Jelly Bean"), _("Blue")],
        ["BBD0C9", _("Jet Stream"), _("Green")],
        ["136843", _("Jewel"), _("Green")],
        ["463D3E", _("Jon"), _("Grey")],
        ["EEF293", _("Jonquil"), _("Green")],
        ["7AAAE0", _("Jordy Blue"), _("Blue")],
        ["5D5346", _("Judge Grey"), _("Brown")],
        ["878785", _("Jumbo"), _("Grey")],
        ["29AB87", _("Jungle Green"), _("Green")],
        ["B0C4C4", _("Jungle Mist"), _("Green")],
        ["74918E", _("Juniper"), _("Green")],
        ["DCBFAC", _("Just Right"), _("Orange")],
        ["6C5E53", _("Kabul"), _("Brown")],
        ["245336", _("Kaitoke Green"), _("Green")],
        ["C5C3B0", _("Kangaroo"), _("Green")],
        ["2D2D24", _("Karaka"), _("Green")],
        ["FEDCC1", _("Karry"), _("Orange")],
        ["576D8E", _("Kashmir Blue"), _("Blue")],
        ["4CBB17", _("Kelly Green"), _("Green")],
        ["4D503C", _("Kelp"), _("Green")],
        ["6C322E", _("Kenyan Copper"), _("Red")],
        ["5FB69C", _("Keppel"), _("Green")],
        ["F0E68C", _("Khaki"), _("Yellow")],
        ["BFC0AB", _("Kidnapper"), _("Green")],
        ["3A3532", _("Kilamanjaro"), _("Grey")],
        ["49764F", _("Killarney"), _("Green")],
        ["695D87", _("Kimberly"), _("Violet")],
        ["583580", _("Kingfisher Daisy"), _("Violet")],
        ["E093AB", _("Kobi"), _("Red")],
        ["7B785A", _("Kokoda"), _("Green")],
        ["804E2C", _("Korma"), _("Orange")],
        ["FEB552", _("Koromiko"), _("Yellow")],
        ["F9D054", _("Kournikova"), _("Yellow")],
        ["428929", _("La Palma"), _("Green")],
        ["BAC00E", _("La Rioja"), _("Green")],
        ["C6DA36", _("Las Palmas"), _("Green")],
        ["C6A95E", _("Laser"), _("Yellow")],
        ["FFFF66", _("Laser Lemon"), _("Yellow")],
        ["6E8D71", _("Laurel"), _("Green")],
        ["E6E6FA", _("Lavender"), _("Violet")],
        ["CCCCFF", _("Lavender Blue"), _("Blue")],
        ["FFF0F5", _("Lavender Blush"), _("Violet")],
        ["BDBBD7", _("Lavender Grey"), _("Grey")],
        ["FBAED2", _("Lavender Pink"), _("Red")],
        ["FBA0E3", _("Lavender Rose"), _("Red")],
        ["7CFC00", _("Lawn Green"), _("Green")],
        ["906A54", _("Leather"), _("Brown")],
        ["FDE910", _("Lemon"), _("Yellow")],
        ["FFFACD", _("Lemon Chiffon"), _("Yellow")],
        ["968428", _("Lemon Ginger"), _("Yellow")],
        ["999A86", _("Lemon Grass"), _("Green")],
        ["2E3749", _("Licorice"), _("Blue")],
        ["ADD8E6", _("Light Blue"), _("Blue")],
        ["F08080", _("Light Coral"), _("Orange")],
        ["E0FFFF", _("Light Cyan"), _("Blue")],
        ["EEDD82", _("Light Goldenrod"), _("Yellow")],
        ["FAFAD2", _("Light Goldenrod Yellow"), _("Yellow")],
        ["90EE90", _("Light Green"), _("Green")],
        ["D3D3D3", _("Light Grey"), _("Grey")],
        ["FFB6C1", _("Light Pink"), _("Red")],
        ["FFA07A", _("Light Salmon"), _("Orange")],
        ["20B2AA", _("Light Sea Green"), _("Green")],
        ["87CEFA", _("Light Sky Blue"), _("Blue")],
        ["8470FF", _("Light Slate Blue"), _("Blue")],
        ["778899", _("Light Slate Grey"), _("Grey")],
        ["B0C4DE", _("Light Steel Blue"), _("Blue")],
        ["856363", _("Light Wood"), _("Brown")],
        ["FFFFE0", _("Light Yellow"), _("Yellow")],
        ["F7A233", _("Lightning Yellow"), _("Yellow")],
        ["C8A2C8", _("Lilac"), _("Violet")],
        ["9470C4", _("Lilac Bush"), _("Violet")],
        ["C19FB3", _("Lily"), _("Violet")],
        ["E9EEEB", _("Lily White"), _("Grey")],
        ["7AAC21", _("Lima"), _("Green")],
        ["00FF00", _("Lime"), _("Green")],
        ["32CD32", _("Lime Green"), _("Green")],
        ["5F9727", _("Limeade"), _("Green")],
        ["89AC27", _("Limerick"), _("Green")],
        ["FAF0E6", _("Linen"), _("White")],
        ["C7CDD8", _("Link Water"), _("Blue")],
        ["962C54", _("Lipstick"), _("Red")],
        ["534B4F", _("Liver"), _("Brown")],
        ["312A29", _("Livid Brown"), _("Brown")],
        ["DBD9C2", _("Loafer"), _("Green")],
        ["B3BBB7", _("Loblolly"), _("Green")],
        ["489084", _("Lochinvar"), _("Green")],
        ["316EA0", _("Lochmara"), _("Blue")],
        ["A2A580", _("Locust"), _("Green")],
        ["393E2E", _("Log Cabin"), _("Green")],
        ["9D9CB4", _("Logan"), _("Blue")],
        ["B9ACBB", _("Lola"), _("Violet")],
        ["AE94AB", _("London Hue"), _("Violet")],
        ["522426", _("Lonestar"), _("Red")],
        ["8B504B", _("Lotus"), _("Brown")],
        ["4C3347", _("Loulou"), _("Violet")],
        ["AB9A1C", _("Lucky"), _("Green")],
        ["292D4F", _("Lucky Point"), _("Blue")],
        ["4E5541", _("Lunar Green"), _("Green")],
        ["782E2C", _("Lusty"), _("Red")],
        ["AB8D3F", _("Luxor Gold"), _("Yellow")],
        ["697D89", _("Lynch"), _("Blue")],
        ["CBE8E8", _("Mabel"), _("Blue")],
        ["FFB97B", _("Macaroni And Cheese"), _("Orange")],
        ["B7E3A8", _("Madang"), _("Green")],
        ["2D3C54", _("Madison"), _("Blue")],
        ["473E23", _("Madras"), _("Brown")],
        ["FF00FF", _("Magenta"), _("Violet")],
        ["AAF0D1", _("Magic Mint"), _("Green")],
        ["F8F4FF", _("Magnolia"), _("White")],
        ["CA3435", _("Mahogany"), _("Brown")],
        ["A56531", _("Mai Tai"), _("Orange")],
        ["2A2922", _("Maire"), _("Yellow")],
        ["E3B982", _("Maize"), _("Yellow")],
        ["695F50", _("Makara"), _("Brown")],
        ["505555", _("Mako"), _("Grey")],
        ["0BDA51", _("Malachite"), _("Green")],
        ["97976F", _("Malachite Green"), _("Green")],
        ["66B7E1", _("Malibu"), _("Blue")],
        ["3A4531", _("Mallard"), _("Green")],
        ["A59784", _("Malta"), _("Brown")],
        ["766D7C", _("Mamba"), _("Violet")],
        ["8D90A1", _("Manatee"), _("Blue")],
        ["B57B2E", _("Mandalay"), _("Yellow")],
        ["8E2323", _("Mandarian Orange"), _("Orange")],
        ["CD525B", _("Mandy"), _("Red")],
        ["F5B799", _("Mandys Pink"), _("Orange")],
        ["E77200", _("Mango Tango"), _("Orange")],
        ["E2AF80", _("Manhattan"), _("Orange")],
        ["7FC15C", _("Mantis"), _("Green")],
        ["96A793", _("Mantle"), _("Green")],
        ["E4DB55", _("Manz"), _("Green")],
        ["352235", _("Mardi Gras"), _("Violet")],
        ["B88A3D", _("Marigold"), _("Yellow")],
        ["42639F", _("Mariner"), _("Blue")],
        ["800000", _("Maroon"), _("Brown")],
        ["2B2E26", _("Marshland"), _("Green")],
        ["B7A8A3", _("Martini"), _("Brown")],
        ["3C3748", _("Martinique"), _("Violet")],
        ["EBC881", _("Marzipan"), _("Yellow")],
        ["57534B", _("Masala"), _("Brown")],
        ["365C7D", _("Matisse"), _("Blue")],
        ["8E4D45", _("Matrix"), _("Red")],
        ["524B4B", _("Matterhorn"), _("Grey")],
        ["E0B0FF", _("Mauve"), _("Violet")],
        ["915F6D", _("Mauve Taupe"), _("Red")],
        ["F091A9", _("Mauvelous"), _("Red")],
        ["C8B1C0", _("Maverick"), _("Violet")],
        ["73C2FB", _("Maya Blue"), _("Blue")],
        ["8C6338", _("McKenzie"), _("Orange")],
        ["66CDAA", _("Medium Aquamarine"), _("Blue")],
        ["0000CD", _("Medium Blue"), _("Blue")],
        ["AF4035", _("Medium Carmine"), _("Red")],
        ["EAEAAE", _("Medium Goldenrod"), _("Yellow")],
        ["BA55D3", _("Medium Orchid"), _("Violet")],
        ["9370DB", _("Medium Purple"), _("Violet")],
        ["3CB371", _("Medium Sea Green"), _("Green")],
        ["7B68EE", _("Medium Slate Blue"), _("Blue")],
        ["00FA9A", _("Medium Spring Green"), _("Green")],
        ["48D1CC", _("Medium Turquoise"), _("Blue")],
        ["C71585", _("Medium Violet Red"), _("Red")],
        ["A68064", _("Medium Wood"), _("Brown")],
        ["E0B7C2", _("Melanie"), _("Red")],
        ["342931", _("Melanzane"), _("Violet")],
        ["FEBAAD", _("Melon"), _("Red")],
        ["C3B9DD", _("Melrose"), _("Violet")],
        ["D5D2D1", _("Mercury"), _("Grey")],
        ["E1DBD0", _("Merino"), _("Yellow")],
        ["4F4E48", _("Merlin"), _("Grey")],
        ["73343A", _("Merlot"), _("Red")],
        ["554A3C", _("Metallic Bronze"), _("Red")],
        ["6E3D34", _("Metallic Copper"), _("Red")],
        ["D4AF37", _("Metallic Gold"), _("Yellow")],
        ["BB7431", _("Meteor"), _("Orange")],
        ["4A3B6A", _("Meteorite"), _("Violet")],
        ["9B3D3D", _("Mexican Red"), _("Red")],
        ["666A6D", _("Mid Grey"), _("Grey")],
        ["21303E", _("Midnight"), _("Blue")],
        ["191970", _("Midnight Blue"), _("Blue")],
        ["21263A", _("Midnight Express"), _("Blue")],
        ["242E28", _("Midnight Moss"), _("Green")],
        ["3F3623", _("Mikado"), _("Brown")],
        ["F6F493", _("Milan"), _("Green")],
        ["9E3332", _("Milano Red"), _("Red")],
        ["F3E5C0", _("Milk Punch"), _("Yellow")],
        ["DCD9CD", _("Milk White"), _("Grey")],
        ["595648", _("Millbrook"), _("Brown")],
        ["F5F5CC", _("Mimosa"), _("Green")],
        ["DAEA6F", _("Mindaro"), _("Green")],
        ["373E41", _("Mine Shaft"), _("Blue")],
        ["506355", _("Mineral Green"), _("Green")],
        ["407577", _("Ming"), _("Green")],
        ["3E3267", _("Minsk"), _("Violet")],
        ["F5FFFA", _("Mint Cream"), _("White")],
        ["98FF98", _("Mint Green"), _("Green")],
        ["E0D8A7", _("Mint Julep"), _("Green")],
        ["C6EADD", _("Mint Tulip"), _("Green")],
        ["373F43", _("Mirage"), _("Blue")],
        ["A5A9B2", _("Mischka"), _("Blue")],
        ["BAB9A9", _("Mist Grey"), _("Grey")],
        ["FFE4E1", _("Misty Rose"), _("Violet")],
        ["605A67", _("Mobster"), _("Violet")],
        ["582F2B", _("Moccaccino"), _("Red")],
        ["FFE4B5", _("Moccasin"), _("Yellow")],
        ["6F372D", _("Mocha"), _("Red")],
        ["97463C", _("Mojo"), _("Red")],
        ["FF9889", _("Mona Lisa"), _("Red")],
        ["6B252C", _("Monarch"), _("Red")],
        ["554D42", _("Mondo"), _("Brown")],
        ["A58B6F", _("Mongoose"), _("Brown")],
        ["7A7679", _("Monsoon"), _("Grey")],
        ["393B3C", _("Montana"), _("Grey")],
        ["7AC5B4", _("Monte Carlo"), _("Green")],
        ["8378C7", _("Moody Blue"), _("Violet")],
        ["F5F3CE", _("Moon Glow"), _("Green")],
        ["CECDB8", _("Moon Mist"), _("Green")],
        ["C0B2D7", _("Moon Raker"), _("Violet")],
        ["F0C420", _("Moon Yellow"), _("Yellow")],
        ["9ED1D3", _("Morning Glory"), _("Blue")],
        ["442D21", _("Morocco Brown"), _("Brown")],
        ["565051", _("Mortar"), _("Grey")],
        ["005F5B", _("Mosque"), _("Green")],
        ["ADDFAD", _("Moss Green"), _("Green")],
        ["1AB385", _("Mountain Meadow"), _("Green")],
        ["A09F9C", _("Mountain Mist"), _("Grey")],
        ["997A8D", _("Mountbatten Pink"), _("Violet")],
        ["A9844F", _("Muddy Waters"), _("Yellow")],
        ["9E7E53", _("Muesli"), _("Brown")],
        ["C54B8C", _("Mulberry"), _("Violet")],
        ["884F40", _("Mule Fawn"), _("Brown")],
        ["524D5B", _("Mulled Wine"), _("Violet")],
        ["FFDB58", _("Mustard"), _("Yellow")],
        ["D68B80", _("My Pink"), _("Red")],
        ["FDAE45", _("My Sin"), _("Yellow")],
        ["21421E", _("Myrtle"), _("Green")],
        ["D8DDDA", _("Mystic"), _("Grey")],
        ["4E5D4E", _("Nandor"), _("Green")],
        ["A39A87", _("Napa"), _("Yellow")],
        ["E9E6DC", _("Narvik"), _("Green")],
        ["FFDEAD", _("Navajo White"), _("Brown")],
        ["000080", _("Navy"), _("Blue")],
        ["0066CC", _("Navy Blue"), _("Blue")],
        ["B8C6BE", _("Nebula"), _("Green")],
        ["EEC7A2", _("Negroni"), _("Orange")],
        ["4D4DFF", _("Neon Blue"), _("Blue")],
        ["FF9933", _("Neon Carrot"), _("Orange")],
        ["FF6EC7", _("Neon Pink"), _("Violet")],
        ["93AAB9", _("Nepal"), _("Blue")],
        ["77A8AB", _("Neptune"), _("Green")],
        ["252525", _("Nero"), _("Grey")],
        ["AAA583", _("Neutral Green"), _("Green")],
        ["666F6F", _("Nevada"), _("Grey")],
        ["6D3B24", _("New Amber"), _("Orange")],
        ["00009C", _("New Midnight Blue"), _("Blue")],
        ["E4C385", _("New Orleans"), _("Yellow")],
        ["EBC79E", _("New Tan"), _("Brown")],
        ["DD8374", _("New York Pink"), _("Red")],
        ["29A98B", _("Niagara"), _("Green")],
        ["332E2E", _("Night Rider"), _("Grey")],
        ["A23D54", _("Night Shadz"), _("Red")],
        ["253F4E", _("Nile Blue"), _("Blue")],
        ["A99D9D", _("Nobel"), _("Grey")],
        ["A19986", _("Nomad"), _("Yellow")],
        ["1D393C", _("Nordic"), _("Blue")],
        ["A4B88F", _("Norway"), _("Green")],
        ["BC9229", _("Nugget"), _("Yellow")],
        ["7E4A3B", _("Nutmeg"), _("Brown")],
        ["FCEDC5", _("Oasis"), _("Yellow")],
        ["008F70", _("Observatory"), _("Green")],
        ["4CA973", _("Ocean Green"), _("Green")],
        ["CC7722", _("Ochre"), _("Brown")],
        ["DFF0E2", _("Off Green"), _("Green")],
        ["FAF3DC", _("Off Yellow"), _("Yellow")],
        ["313330", _("Oil"), _("Grey")],
        ["8A3335", _("Old Brick"), _("Red")],
        ["73503B", _("Old Copper"), _("Red")],
        ["CFB53B", _("Old Gold"), _("Yellow")],
        ["FDF5E6", _("Old Lace"), _("White")],
        ["796878", _("Old Lavender"), _("Violet")],
        ["C02E4C", _("Old Rose"), _("Red")],
        ["808000", _("Olive"), _("Green")],
        ["6B8E23", _("Olive Drab"), _("Green")],
        ["B5B35C", _("Olive Green"), _("Green")],
        ["888064", _("Olive Haze"), _("Yellow")],
        ["747028", _("Olivetone"), _("Green")],
        ["9AB973", _("Olivine"), _("Orange")],
        ["C2E6EC", _("Onahau"), _("Blue")],
        ["48412B", _("Onion"), _("Yellow")],
        ["A8C3BC", _("Opal"), _("Green")],
        ["987E7E", _("Opium"), _("Brown")],
        ["395555", _("Oracle"), _("Green")],
        ["FFA500", _("Orange"), _("Orange")],
        ["FFA000", _("Orange Peel"), _("Orange")],
        ["FF4500", _("Orange Red"), _("Orange")],
        ["A85335", _("Orange Roughy"), _("Orange")],
        ["EAE3CD", _("Orange White"), _("Yellow")],
        ["DA70D6", _("Orchid"), _("Violet")],
        ["F1EBD9", _("Orchid White"), _("Yellow")],
        ["255B77", _("Orient"), _("Blue")],
        ["C28E88", _("Oriental Pink"), _("Red")],
        ["D2D3B3", _("Orinoco"), _("Green")],
        ["818988", _("Oslo Grey"), _("Grey")],
        ["D3DBCB", _("Ottoman"), _("Green")],
        ["2D383A", _("Outer Space"), _("Grey")],
        ["FF6037", _("Outrageous Orange"), _("Orange")],
        ["28353A", _("Oxford Blue"), _("Blue")],
        ["6D9A78", _("Oxley"), _("Green")],
        ["D1EAEA", _("Oyster Bay"), _("Blue")],
        ["D4B5B0", _("Oyster Pink"), _("Red")],
        ["864B36", _("Paarl"), _("Orange")],
        ["7A715C", _("Pablo"), _("Yellow")],
        ["009DC4", _("Pacific Blue"), _("Blue")],
        ["4F4037", _("Paco"), _("Brown")],
        ["7EB394", _("Padua"), _("Green")],
        ["682860", _("Palatinate Purple"), _("Violet")],
        ["987654", _("Pale Brown"), _("Brown")],
        ["DDADAF", _("Pale Chestnut"), _("Red")],
        ["ABCDEF", _("Pale Cornflower Blue"), _("Blue")],
        ["EEE8AA", _("Pale Goldenrod"), _("Yellow")],
        ["98FB98", _("Pale Green"), _("Green")],
        ["BDCAA8", _("Pale Leaf"), _("Green")],
        ["F984E5", _("Pale Magenta"), _("Violet")],
        ["9C8D72", _("Pale Oyster"), _("Brown")],
        ["FADADD", _("Pale Pink"), _("Red")],
        ["F9F59F", _("Pale Prim"), _("Green")],
        ["EFD6DA", _("Pale Rose"), _("Red")],
        ["636D70", _("Pale Sky"), _("Blue")],
        ["C3BEBB", _("Pale Slate"), _("Grey")],
        ["BC987E", _("Pale Taupe"), _("Grey")],
        ["AFEEEE", _("Pale Turquoise"), _("Blue")],
        ["DB7093", _("Pale Violet Red"), _("Red")],
        ["20392C", _("Palm Green"), _("Green")],
        ["36482F", _("Palm Leaf"), _("Green")],
        ["EAE4DC", _("Pampas"), _("Grey")],
        ["EBF7E4", _("Panache"), _("Green")],
        ["DFB992", _("Pancho"), _("Orange")],
        ["544F3A", _("Panda"), _("Yellow")],
        ["FFEFD5", _("Papaya Whip"), _("Yellow")],
        ["7C2D37", _("Paprika"), _("Red")],
        ["488084", _("Paradiso"), _("Green")],
        ["D0C8B0", _("Parchment"), _("Yellow")],
        ["FBEB50", _("Paris Daisy"), _("Green")],
        ["312760", _("Paris M"), _("Violet")],
        ["BFCDC0", _("Paris White"), _("Green")],
        ["305D35", _("Parsley"), _("Green")],
        ["77DD77", _("Pastel Green"), _("Green")],
        ["639283", _("Patina"), _("Green")],
        ["D3E5EF", _("Pattens Blue"), _("Blue")],
        ["2A2551", _("Paua"), _("Violet")],
        ["BAAB87", _("Pavlova"), _("Yellow")],
        ["404048", _("Payne's Grey"), _("Grey")],
        ["FFCBA4", _("Peach"), _("Orange")],
        ["FFDAB9", _("Peach Puff"), _("Yellow")],
        ["FFCC99", _("Peach-Orange"), _("Orange")],
        ["FADFAD", _("Peach-Yellow"), _("Yellow")],
        ["7A4434", _("Peanut"), _("Brown")],
        ["D1E231", _("Pear"), _("Yellow")],
        ["DED1C6", _("Pearl Bush"), _("Orange")],
        ["EAE0C8", _("Pearl Lusta"), _("Yellow")],
        ["766D52", _("Peat"), _("Yellow")],
        ["2599B2", _("Pelorous"), _("Blue")],
        ["D7E7D0", _("Peppermint"), _("Green")],
        ["ACB9E8", _("Perano"), _("Blue")],
        ["C2A9DB", _("Perfume"), _("Violet")],
        ["ACB6B2", _("Periglacial Blue"), _("Green")],
        ["C3CDE6", _("Periwinkle"), _("Blue")],
        ["1C39BB", _("Persian Blue"), _("Blue")],
        ["00A693", _("Persian Green"), _("Green")],
        ["32127A", _("Persian Indigo"), _("Violet")],
        ["F77FBE", _("Persian Pink"), _("Red")],
        ["683332", _("Persian Plum"), _("Red")],
        ["CC3333", _("Persian Red"), _("Red")],
        ["FE28A2", _("Persian Rose"), _("Red")],
        ["EC5800", _("Persimmon"), _("Red")],
        ["CD853F", _("Peru"), _("Brown")],
        ["733D1F", _("Peru Tan"), _("Orange")],
        ["7A7229", _("Pesto"), _("Yellow")],
        ["DA9790", _("Petite Orchid"), _("Red")],
        ["91A092", _("Pewter"), _("Green")],
        ["826663", _("Pharlap"), _("Brown")],
        ["F8EA97", _("Picasso"), _("Green")],
        ["5BA0D0", _("Picton Blue"), _("Blue")],
        ["FDD7E4", _("Pig Pink"), _("Red")],
        ["00A550", _("Pigment Green"), _("Green")],
        ["756556", _("Pine Cone"), _("Brown")],
        ["BDC07E", _("Pine Glade"), _("Green")],
        ["01796F", _("Pine Green"), _("Green")],
        ["2A2F23", _("Pine Tree"), _("Green")],
        ["FFC0CB", _("Pink"), _("Red")],
        ["FF66FF", _("Pink Flamingo"), _("Red")],
        ["D8B4B6", _("Pink Flare"), _("Red")],
        ["F6CCD7", _("Pink Lace"), _("Red")],
        ["F3D7B6", _("Pink Lady"), _("Orange")],
        ["BFB3B2", _("Pink Swan"), _("Grey")],
        ["9D5432", _("Piper"), _("Orange")],
        ["F5E6C4", _("Pipi"), _("Yellow")],
        ["FCDBD2", _("Pippin"), _("Red")],
        ["BA782A", _("Pirate Gold"), _("Yellow")],
        ["BBCDA5", _("Pixie Green"), _("Green")],
        ["E57F3D", _("Pizazz"), _("Orange")],
        ["BF8D3C", _("Pizza"), _("Yellow")],
        ["3E594C", _("Plantation"), _("Green")],
        ["DDA0DD", _("Plum"), _("Violet")],
        ["651C26", _("Pohutukawa"), _("Red")],
        ["E5F2E7", _("Polar"), _("Green")],
        ["8AA7CC", _("Polo Blue"), _("Blue")],
        ["6A1F44", _("Pompadour"), _("Violet")],
        ["DDDCDB", _("Porcelain"), _("Grey")],
        ["DF9D5B", _("Porsche"), _("Orange")],
        ["3B436C", _("Port Gore"), _("Blue")],
        ["F4F09B", _("Portafino"), _("Green")],
        ["8B98D8", _("Portage"), _("Blue")],
        ["F0D555", _("Portica"), _("Yellow")],
        ["EFDCD4", _("Pot Pourri"), _("Orange")],
        ["845C40", _("Potters Clay"), _("Brown")],
        ["B0E0E6", _("Powder Blue"), _("Blue")],
        ["883C32", _("Prairie Sand"), _("Red")],
        ["CAB4D4", _("Prelude"), _("Violet")],
        ["E2CDD5", _("Prim"), _("Violet")],
        ["E4DE8E", _("Primrose"), _("Green")],
        ["F8F6DF", _("Promenade"), _("Green")],
        ["F6E3DA", _("Provincial Pink"), _("Orange")],
        ["003366", _("Prussian Blue"), _("Blue")],
        ["DD00FF", _("Psychedelic Purple"), _("Violet")],
        ["CC8899", _("Puce"), _("Red")],
        ["6E3326", _("Pueblo"), _("Orange")],
        ["59BAA3", _("Puerto Rico"), _("Green")],
        ["BAC0B4", _("Pumice"), _("Green")],
        ["FF7518", _("Pumpkin"), _("Orange")],
        ["534931", _("Punga"), _("Yellow")],
        ["800080", _("Purple"), _("Violet")],
        ["652DC1", _("Purple Heart"), _("Violet")],
        ["9678B6", _("Purple Mountain's Majesty"), _("Violet")],
        ["50404D", _("Purple Taupe"), _("Grey")],
        ["CDAE70", _("Putty"), _("Yellow")],
        ["F2EDDD", _("Quarter Pearl Lusta"), _("Green")],
        ["EBE2D2", _("Quarter Spanish White"), _("Yellow")],
        ["D9D9F3", _("Quartz"), _("White")],
        ["C3988B", _("Quicksand"), _("Brown")],
        ["CBC9C0", _("Quill Grey"), _("Grey")],
        ["6A5445", _("Quincy"), _("Brown")],
        ["232F2C", _("Racing Green"), _("Green")],
        ["FF355E", _("Radical Red"), _("Red")],
        ["DCC6A0", _("Raffia"), _("Yellow")],
        ["667028", _("Rain Forest"), _("Green")],
        ["B3C1B1", _("Rainee"), _("Green")],
        ["FCAE60", _("Rajah"), _("Orange")],
        ["2B2E25", _("Rangoon Green"), _("Green")],
        ["6F747B", _("Raven"), _("Blue")],
        ["D27D46", _("Raw Sienna"), _("Brown")],
        ["734A12", _("Raw Umber"), _("Brown")],
        ["FF33CC", _("Razzle Dazzle Rose"), _("Red")],
        ["E30B5C", _("Razzmatazz"), _("Red")],
        ["453430", _("Rebel"), _("Brown")],
        ["FF0000", _("Red"), _("Red")],
        ["701F28", _("Red Berry"), _("Red")],
        ["CB6F4A", _("Red Damask"), _("Orange")],
        ["662A2C", _("Red Devil"), _("Red")],
        ["FF3F34", _("Red Orange"), _("Orange")],
        ["5D1F1E", _("Red Oxide"), _("Red")],
        ["7D4138", _("Red Robin"), _("Red")],
        ["AD522E", _("Red Stage"), _("Orange")],
        ["BB3385", _("Medium Red Violet"), _("Violet")],
        ["5B342E", _("Redwood"), _("Red")],
        ["D1EF9F", _("Reef"), _("Green")],
        ["A98D36", _("Reef Gold"), _("Yellow")],
        ["203F58", _("Regal Blue"), _("Blue")],
        ["798488", _("Regent Grey"), _("Blue")],
        ["A0CDD9", _("Regent St Blue"), _("Blue")],
        ["F6DEDA", _("Remy"), _("Red")],
        ["B26E33", _("Reno Sand"), _("Orange")],
        ["323F75", _("Resolution Blue"), _("Blue")],
        ["37363F", _("Revolver"), _("Violet")],
        ["3D4653", _("Rhino"), _("Blue")],
        ["EFECDE", _("Rice Cake"), _("Green")],
        ["EFF5D1", _("Rice Flower"), _("Green")],
        ["5959AB", _("Rich Blue"), _("Blue")],
        ["A15226", _("Rich Gold"), _("Orange")],
        ["B7C61A", _("Rio Grande"), _("Green")],
        ["89D9C8", _("Riptide"), _("Green")],
        ["556061", _("River Bed"), _("Blue")],
        ["DDAD56", _("Rob Roy"), _("Yellow")],
        ["00CCCC", _("Robin's Egg Blue"), _("Blue")],
        ["5A4D41", _("Rock"), _("Brown")],
        ["93A2BA", _("Rock Blue"), _("Blue")],
        ["9D442D", _("Rock Spray"), _("Orange")],
        ["C7A384", _("Rodeo Dust"), _("Brown")],
        ["6D7876", _("Rolling Stone"), _("Green")],
        ["D8625B", _("Roman"), _("Red")],
        ["7D6757", _("Roman Coffee"), _("Brown")],
        ["F4F0E6", _("Romance"), _("Grey")],
        ["FFC69E", _("Romantic"), _("Orange")],
        ["EAB852", _("Ronchi"), _("Yellow")],
        ["A14743", _("Roof Terracotta"), _("Red")],
        ["8E593C", _("Rope"), _("Orange")],
        ["D3A194", _("Rose"), _("Red")],
        ["FEAB9A", _("Rose Bud"), _("Red")],
        ["8A2D52", _("Rose Bud Cherry"), _("Red")],
        ["AC512D", _("Rose Of Sharon"), _("Orange")],
        ["905D5D", _("Rose Taupe"), _("Violet")],
        ["FBEEE8", _("Rose White"), _("Red")],
        ["BC8F8F", _("Rosy Brown"), _("Brown")],
        ["B69642", _("Roti"), _("Yellow")],
        ["A94064", _("Rouge"), _("Red")],
        ["4169E1", _("Royal Blue"), _("Blue")],
        ["B54B73", _("Royal Heath"), _("Red")],
        ["6B3FA0", _("Royal Purple"), _("Violet")],
        ["E0115F", _("Ruby"), _("Red")],
        ["716675", _("Rum"), _("Violet")],
        ["F1EDD4", _("Rum Swizzle"), _("Green")],
        ["80461B", _("Russet"), _("Brown")],
        ["7D655C", _("Russett"), _("Brown")],
        ["B7410E", _("Rust"), _("Red")],
        ["3A181A", _("Rustic Red"), _("Red")],
        ["8D5F2C", _("Rusty Nail"), _("Orange")],
        ["5D4E46", _("Saddle"), _("Brown")],
        ["8B4513", _("Saddle Brown"), _("Brown")],
        ["FF6600", _("Safety Orange"), _("Orange")],
        ["F4C430", _("Saffron"), _("Yellow")],
        ["989F7A", _("Sage"), _("Green")],
        ["B79826", _("Sahara"), _("Yellow")],
        ["A5CEEC", _("Sail"), _("Blue")],
        ["177B4D", _("Salem"), _("Green")],
        ["FA8072", _("Salmon"), _("Red")],
        ["FFD67B", _("Salomie"), _("Yellow")],
        ["696268", _("Salt Box"), _("Violet")],
        ["EEF3E5", _("Saltpan"), _("Grey")],
        ["3B2E25", _("Sambuca"), _("Brown")],
        ["2C6E31", _("San Felix"), _("Green")],
        ["445761", _("San Juan"), _("Blue")],
        ["4E6C9D", _("San Marino"), _("Blue")],
        ["867665", _("Sand Dune"), _("Brown")],
        ["A3876A", _("Sandal"), _("Brown")],
        ["AF937D", _("Sandrift"), _("Brown")],
        ["786D5F", _("Sandstone"), _("Brown")],
        ["DECB81", _("Sandwisp"), _("Yellow")],
        ["FEDBB7", _("Sandy Beach"), _("Orange")],
        ["F4A460", _("Sandy Brown"), _("Brown")],
        ["92000A", _("Sangria"), _("Red")],
        ["6C3736", _("Sanguine Brown"), _("Red")],
        ["9998A7", _("Santas Grey"), _("Blue")],
        ["A96A50", _("Sante Fe"), _("Orange")],
        ["E1D5A6", _("Sapling"), _("Yellow")],
        ["082567", _("Sapphire"), _("Blue")],
        ["555B2C", _("Saratoga"), _("Green")],
        ["F4EAE4", _("Sauvignon"), _("Red")],
        ["F5DEC4", _("Sazerac"), _("Orange")],
        ["6F63A0", _("Scampi"), _("Violet")],
        ["ADD9D1", _("Scandal"), _("Green")],
        ["FF2400", _("Scarlet"), _("Red")],
        ["4A2D57", _("Scarlet Gum"), _("Violet")],
        ["7E2530", _("Scarlett"), _("Red")],
        ["6B6A6C", _("Scarpa Flow"), _("Grey")],
        ["87876F", _("Schist"), _("Green")],
        ["FFD800", _("School Bus Yellow"), _("Yellow")],
        ["8D8478", _("Schooner"), _("Brown")],
        ["308EA0", _("Scooter"), _("Blue")],
        ["6A6466", _("Scorpion"), _("Grey")],
        ["EEE7C8", _("Scotch Mist"), _("Yellow")],
        ["66FF66", _("Screamin' Green"), _("Green")],
        ["3D4031", _("Scrub"), _("Green")],
        ["EF9548", _("Sea Buckthorn"), _("Orange")],
        ["DFDDD6", _("Sea Fog"), _("Grey")],
        ["2E8B57", _("Sea Green"), _("Green")],
        ["C2D5C4", _("Sea Mist"), _("Green")],
        ["8AAEA4", _("Sea Nymph"), _("Green")],
        ["DB817E", _("Sea Pink"), _("Red")],
        ["77B7D0", _("Seagull"), _("Blue")],
        ["321414", _("Seal Brown"), _("Brown")],
        ["69326E", _("Seance"), _("Violet")],
        ["FFF5EE", _("Seashell"), _("White")],
        ["37412A", _("Seaweed"), _("Green")],
        ["E6DFE7", _("Selago"), _("Violet")],
        ["FFBA00", _("Selective Yellow"), _("Yellow")],
        ["6B4226", _("Semi-Sweet Chocolate"), _("Brown")],
        ["9E5B40", _("Sepia"), _("Brown")],
        ["FCE9D7", _("Serenade"), _("Orange")],
        ["837050", _("Shadow"), _("Green")],
        ["9AC0B6", _("Shadow Green"), _("Green")],
        ["9F9B9D", _("Shady Lady"), _("Grey")],
        ["609AB8", _("Shakespeare"), _("Blue")],
        ["F8F6A8", _("Shalimar"), _("Green")],
        ["33CC99", _("Shamrock"), _("Green")],
        ["009E60", _("Shamrock Green"), _("Green")],
        ["34363A", _("Shark"), _("Grey")],
        ["00494E", _("Sherpa Blue"), _("Green")],
        ["1B4636", _("Sherwood Green"), _("Green")],
        ["E6B2A6", _("Shilo"), _("Red")],
        ["745937", _("Shingle Fawn"), _("Brown")],
        ["7988AB", _("Ship Cove"), _("Blue")],
        ["4E4E4C", _("Ship Grey"), _("Grey")],
        ["842833", _("Shiraz"), _("Red")],
        ["E899BE", _("Shocking"), _("Violet")],
        ["FC0FC0", _("Shocking Pink"), _("Red")],
        ["61666B", _("Shuttle Grey"), _("Grey")],
        ["686B50", _("Siam"), _("Green")],
        ["E9D9A9", _("Sidecar"), _("Yellow")],
        ["A0522D", _("Sienna"), _("Brown")],
        ["BBADA1", _("Silk"), _("Brown")],
        ["C0C0C0", _("Silver"), _("Grey")],
        ["ACAEA9", _("Silver Chalice"), _("Grey")],
        ["BEBDB6", _("Silver Sand"), _("Grey")],
        ["67BE90", _("Silver Tree"), _("Green")],
        ["A6D5D0", _("Sinbad"), _("Green")],
        ["69293B", _("Siren"), _("Red")],
        ["68766E", _("Sirocco"), _("Green")],
        ["C5BAA0", _("Sisal"), _("Yellow")],
        ["9DB4AA", _("Skeptic"), _("Green")],
        ["87CEEB", _("Sky Blue"), _("Blue")],
        ["6A5ACD", _("Slate Blue"), _("Blue")],
        ["708090", _("Slate Grey"), _("Grey")],
        ["42342B", _("Slugger"), _("Brown")],
        ["003399", _("Smalt"), _("Blue")],
        ["496267", _("Smalt Blue"), _("Blue")],
        ["BB5F34", _("Smoke Tree"), _("Orange")],
        ["605D6B", _("Smoky"), _("Violet")],
        ["FFFAFA", _("Snow"), _("White")],
        ["E3E3DC", _("Snow Drift"), _("Grey")],
        ["EAF7C9", _("Snow Flurry"), _("Green")],
        ["D6F0CD", _("Snowy Mint"), _("Green")],
        ["E4D7E5", _("Snuff"), _("Violet")],
        ["ECE5DA", _("Soapstone"), _("Grey")],
        ["CFBEA5", _("Soft Amber"), _("Yellow")],
        ["EEDFDE", _("Soft Peach"), _("Red")],
        ["85494C", _("Solid Pink"), _("Red")],
        ["EADAC2", _("Solitaire"), _("Yellow")],
        ["E9ECF1", _("Solitude"), _("Blue")],
        ["DD6B38", _("Sorbus"), _("Orange")],
        ["9D7F61", _("Sorrell Brown"), _("Brown")],
        ["C9B59A", _("Sour Dough"), _("Brown")],
        ["6F634B", _("Soya Bean"), _("Brown")],
        ["4B433B", _("Space Shuttle"), _("Brown")],
        ["7B8976", _("Spanish Green"), _("Green")],
        ["DED1B7", _("Spanish White"), _("Yellow")],
        ["375D4F", _("Spectra"), _("Green")],
        ["6C4F3F", _("Spice"), _("Brown")],
        ["8B5F4D", _("Spicy Mix"), _("Brown")],
        ["FF1CAE", _("Spicy Pink"), _("Red")],
        ["B3C4D8", _("Spindle"), _("Blue")],
        ["F1D79E", _("Splash"), _("Yellow")],
        ["7ECDDD", _("Spray"), _("Blue")],
        ["A7FC00", _("Spring Bud"), _("Green")],
        ["00FF7F", _("Spring Green"), _("Green")],
        ["A3BD9C", _("Spring Rain"), _("Green")],
        ["F1F1C6", _("Spring Sun"), _("Green")],
        ["E9E1D9", _("Spring Wood"), _("Grey")],
        ["B8CA9D", _("Sprout"), _("Green")],
        ["A2A1AC", _("Spun Pearl"), _("Blue")],
        ["8F7D6B", _("Squirrel"), _("Brown")],
        ["325482", _("St Tropaz"), _("Blue")],
        ["858885", _("Stack"), _("Grey")],
        ["A0A197", _("Star Dust"), _("Grey")],
        ["D2C6B6", _("Stark White"), _("Yellow")],
        ["E3DD39", _("Starship"), _("Green")],
        ["4682B4", _("Steel Blue"), _("Blue")],
        ["43464B", _("Steel Grey"), _("Grey")],
        ["833D3E", _("Stiletto"), _("Red")],
        ["807661", _("Stonewall"), _("Yellow")],
        ["65645F", _("Storm Dust"), _("Grey")],
        ["747880", _("Storm Grey"), _("Blue")],
        ["DABE82", _("Straw"), _("Yellow")],
        ["946A81", _("Strikemaster"), _("Violet")],
        ["406356", _("Stromboli"), _("Green")],
        ["724AA1", _("Studio"), _("Violet")],
        ["8C9C9C", _("Submarine"), _("Blue")],
        ["EEEFDF", _("Sugar Cane"), _("Green")],
        ["C6EA80", _("Sulu"), _("Green")],
        ["8FB69C", _("Summer Green"), _("Green")],
        ["38B0DE", _("Summer Sky"), _("Blue")],
        ["EF8E38", _("Sun"), _("Orange")],
        ["C4AA4D", _("Sundance"), _("Yellow")],
        ["F8AFA9", _("Sundown"), _("Red")],
        ["DAC01A", _("Sunflower"), _("Yellow")],
        ["C76155", _("Sunglo"), _("Red")],
        ["FFCC33", _("Sunglow"), _("Orange")],
        ["C0514A", _("Sunset"), _("Red")],
        ["FE4C40", _("Sunset Orange"), _("Orange")],
        ["FA9D49", _("Sunshade"), _("Orange")],
        ["FFB437", _("Supernova"), _("Yellow")],
        ["B8D4BB", _("Surf"), _("Green")],
        ["C3D6BD", _("Surf Crest"), _("Green")],
        ["007B77", _("Surfie Green"), _("Green")],
        ["7C9F2F", _("Sushi"), _("Green")],
        ["8B8685", _("Suva Grey"), _("Grey")],
        ["252F2F", _("Swamp"), _("Green")],
        ["DAE6DD", _("Swans Down"), _("Grey")],
        ["F9E176", _("Sweet Corn"), _("Yellow")],
        ["EE918D", _("Sweet Pink"), _("Red")],
        ["D7CEC5", _("Swirl"), _("Grey")],
        ["DBD0CA", _("Swiss Coffee"), _("Grey")],
        ["F6AE78", _("Tacao"), _("Orange")],
        ["D2B960", _("Tacha"), _("Yellow")],
        ["DC722A", _("Tahiti Gold"), _("Orange")],
        ["D8CC9B", _("Tahuna Sands"), _("Yellow")],
        ["853534", _("Tall Poppy"), _("Red")],
        ["A39977", _("Tallow"), _("Yellow")],
        ["752B2F", _("Tamarillo"), _("Red")],
        ["D2B48C", _("Tan"), _("Brown")],
        ["B8B5A1", _("Tana"), _("Green")],
        ["1E2F3C", _("Tangaroa"), _("Blue")],
        ["F28500", _("Tangerine"), _("Orange")],
        ["FFCC00", _("Tangerine Yellow"), _("Yellow")],
        ["D46F31", _("Tango"), _("Orange")],
        ["7C7C72", _("Tapa"), _("Green")],
        ["B37084", _("Tapestry"), _("Red")],
        ["DEF1DD", _("Tara"), _("Green")],
        ["253C48", _("Tarawera"), _("Blue")],
        ["BAC0B3", _("Tasman"), _("Grey")],
        ["483C32", _("Taupe"), _("Grey")],
        ["8B8589", _("Taupe Grey"), _("Grey")],
        ["643A48", _("Tawny Port"), _("Red")],
        ["496569", _("Tax Break"), _("Blue")],
        ["2B4B40", _("Te Papa Green"), _("Green")],
        ["BFB5A2", _("Tea"), _("Yellow")],
        ["D0F0C0", _("Tea Green"), _("Green")],
        ["F883C2", _("Tea Rose"), _("Orange")],
        ["AB8953", _("Teak"), _("Yellow")],
        ["008080", _("Teal"), _("Blue")],
        ["254855", _("Teal Blue"), _("Blue")],
        ["3C2126", _("Temptress"), _("Brown")],
        ["CD5700", _("Tenne (Tawny)"), _("Orange")],
        ["F4D0A4", _("Tequila"), _("Yellow")],
        ["E2725B", _("Terra Cotta"), _("Red")],
        ["ECE67E", _("Texas"), _("Green")],
        ["FCB057", _("Texas Rose"), _("Orange")],
        ["B1948F", _("Thatch"), _("Brown")],
        ["544E31", _("Thatch Green"), _("Yellow")],
        ["D8BFD8", _("Thistle"), _("Violet")],
        ["4D4D4B", _("Thunder"), _("Grey")],
        ["923830", _("Thunderbird"), _("Red")],
        ["97422D", _("Tia Maria"), _("Orange")],
        ["B9C3BE", _("Tiara"), _("Grey")],
        ["184343", _("Tiber"), _("Green")],
        ["FC80A5", _("Tickle Me Pink"), _("Red")],
        ["F0F590", _("Tidal"), _("Green")],
        ["BEB4AB", _("Tide"), _("Brown")],
        ["324336", _("Timber Green"), _("Green")],
        ["D9D6CF", _("Timberwolf"), _("Grey")],
        ["DDD6E1", _("Titan White"), _("Violet")],
        ["9F715F", _("Toast"), _("Brown")],
        ["6D5843", _("Tobacco Brown"), _("Brown")],
        ["44362D", _("Tobago"), _("Brown")],
        ["3E2631", _("Toledo"), _("Violet")],
        ["2D2541", _("Tolopea"), _("Violet")],
        ["4F6348", _("Tom Thumb"), _("Green")],
        ["FF6347", _("Tomato"), _("Red")],
        ["E79E88", _("Tonys Pink"), _("Orange")],
        ["817C87", _("Topaz"), _("Violet")],
        ["FD0E35", _("Torch Red"), _("Red")],
        ["353D75", _("Torea Bay"), _("Blue")],
        ["374E88", _("Tory Blue"), _("Blue")],
        ["744042", _("Tosca"), _("Red")],
        ["9CACA5", _("Tower Grey"), _("Green")],
        ["6DAFA7", _("Tradewind"), _("Green")],
        ["DDEDE9", _("Tranquil"), _("Blue")],
        ["E2DDC7", _("Travertine"), _("Green")],
        ["E2813B", _("Tree Poppy"), _("Orange")],
        ["7E8424", _("Trendy Green"), _("Green")],
        ["805D80", _("Trendy Pink"), _("Violet")],
        ["C54F33", _("Trinidad"), _("Orange")],
        ["AEC9EB", _("Tropical Blue"), _("Blue")],
        ["00755E", _("Tropical Rain Forest"), _("Green")],
        ["4C5356", _("Trout"), _("Grey")],
        ["8E72C7", _("True V"), _("Violet")],
        ["454642", _("Tuatara"), _("Grey")],
        ["F9D3BE", _("Tuft Bush"), _("Orange")],
        ["E3AC3D", _("Tulip Tree"), _("Yellow")],
        ["DEA681", _("Tumbleweed"), _("Brown")],
        ["46494E", _("Tuna"), _("Grey")],
        ["585452", _("Tundora"), _("Grey")],
        ["F5CC23", _("Turbo"), _("Yellow")],
        ["A56E75", _("Turkish Rose"), _("Red")],
        ["AE9041", _("Turmeric"), _("Yellow")],
        ["40E0D0", _("Turquoise"), _("Blue")],
        ["6CDAE7", _("Turquoise Blue"), _("Blue")],
        ["363E1D", _("Turtle Green"), _("Green")],
        ["AD6242", _("Tuscany"), _("Orange")],
        ["E3E5B1", _("Tusk"), _("Green")],
        ["BF914B", _("Tussock"), _("Yellow")],
        ["F8E4E3", _("Tutu"), _("Red")],
        ["DAC0CD", _("Twilight"), _("Violet")],
        ["F4F6EC", _("Twilight Blue"), _("Grey")],
        ["C19156", _("Twine"), _("Yellow")],
        ["66023C", _("Tyrian Purple"), _("Violet")],
        ["FF6FFF", _("Ultra Pink"), _("Red")],
        ["120A8F", _("Ultramarine"), _("Blue")],
        ["D4574E", _("Valencia"), _("Red")],
        ["382C38", _("Valentino"), _("Violet")],
        ["2A2B41", _("Valhalla"), _("Violet")],
        ["523936", _("Van Cleef"), _("Brown")],
        ["CCB69B", _("Vanilla"), _("Brown")],
        ["EBD2D1", _("Vanilla Ice"), _("Red")],
        ["FDEFD3", _("Varden"), _("Yellow")],
        ["C80815", _("Venetian Red"), _("Red")],
        ["2C5778", _("Venice Blue"), _("Blue")],
        ["8B7D82", _("Venus"), _("Violet")],
        ["62603E", _("Verdigris"), _("Grey")],
        ["48531A", _("Verdun Green"), _("Green")],
        ["FF4D00", _("Vermilion"), _("Red")],
        ["5C4033", _("Very Dark Brown"), _("Brown")],
        ["CDCDCD", _("Very Light Grey"), _("Grey")],
        ["A85533", _("Vesuvius"), _("Orange")],
        ["564985", _("Victoria"), _("Violet")],
        ["5F9228", _("Vida Loca"), _("Green")],
        ["4DB1C8", _("Viking"), _("Blue")],
        ["955264", _("Vin Rouge"), _("Red")],
        ["C58F9D", _("Viola"), _("Red")],
        ["2E2249", _("Violent Violet"), _("Violet")],
        ["EE82EE", _("Violet"), _("Violet")],
        ["9F5F9F", _("Violet Blue"), _("Violet")],
        ["F7468A", _("Violet Red"), _("Red")],
        ["40826D", _("Viridian"), _("Blue")],
        ["4B5F56", _("Viridian Green"), _("Green")],
        ["F9E496", _("Vis Vis"), _("Yellow")],
        ["97D5B3", _("Vista Blue"), _("Green")],
        ["E3DFD9", _("Vista White"), _("Grey")],
        ["FF9980", _("Vivid Tangerine"), _("Orange")],
        ["803790", _("Vivid Violet"), _("Violet")],
        ["4E2728", _("Volcano"), _("Red")],
        ["443240", _("Voodoo"), _("Violet")],
        ["36383C", _("Vulcan"), _("Grey")],
        ["D4BBB1", _("Wafer"), _("Orange")],
        ["5B6E91", _("Waikawa Grey"), _("Blue")],
        ["4C4E31", _("Waiouru"), _("Green")],
        ["E4E2DC", _("Wan White"), _("Grey")],
        ["849137", _("Wasabi"), _("Green")],
        ["B6ECDE", _("Water Leaf"), _("Green")],
        ["006E4E", _("Watercourse"), _("Green")],
        ["D6CA3D", _("Wattle"), _("Green")],
        ["F2CDBB", _("Watusi"), _("Orange")],
        ["EEB39E", _("Wax Flower"), _("Orange")],
        ["FDD7D8", _("We Peep"), _("Red")],
        ["4C6B88", _("Wedgewood"), _("Blue")],
        ["8E3537", _("Well Read"), _("Red")],
        ["5C512F", _("West Coast"), _("Yellow")],
        ["E5823A", _("West Side"), _("Orange")],
        ["D4CFC5", _("Westar"), _("Grey")],
        ["F1919A", _("Wewak"), _("Red")],
        ["F5DEB3", _("Wheat"), _("Brown")],
        ["DFD7BD", _("Wheatfield"), _("Yellow")],
        ["D29062", _("Whiskey"), _("Orange")],
        ["D4915D", _("Whiskey Sour"), _("Orange")],
        ["EFE6E6", _("Whisper"), _("Grey")],
        ["FFFFFF", _("White"), _("White")],
        ["D7EEE4", _("White Ice"), _("Green")],
        ["E7E5E8", _("White Lilac"), _("Blue")],
        ["EEE7DC", _("White Linen"), _("Grey")],
        ["F8F6D8", _("White Nectar"), _("Green")],
        ["DAD6CC", _("White Pointer"), _("Grey")],
        ["D4CFB4", _("White Rock"), _("Green")],
        ["F5F5F5", _("White Smoke"), _("White")],
        ["7A89B8", _("Wild Blue Yonder"), _("Blue")],
        ["E3D474", _("Wild Rice"), _("Green")],
        ["E7E4DE", _("Wild Sand"), _("Grey")],
        ["FF3399", _("Wild Strawberry"), _("Red")],
        ["FD5B78", _("Wild Watermelon"), _("Red")],
        ["BECA60", _("Wild Willow"), _("Green")],
        ["53736F", _("William"), _("Green")],
        ["DFE6CF", _("Willow Brook"), _("Green")],
        ["69755C", _("Willow Grove"), _("Green")],
        ["462C77", _("Windsor"), _("Violet")],
        ["522C35", _("Wine Berry"), _("Red")],
        ["D0C383", _("Winter Hazel"), _("Yellow")],
        ["F9E8E2", _("Wisp Pink"), _("Red")],
        ["C9A0DC", _("Wisteria"), _("Violet")],
        ["A29ECD", _("Wistful"), _("Blue")],
        ["FBF073", _("Witch Haze"), _("Green")],
        ["302621", _("Wood Bark"), _("Brown")],
        ["463629", _("Woodburn"), _("Brown")],
        ["626746", _("Woodland"), _("Green")],
        ["45402B", _("Woodrush"), _("Yellow")],
        ["2B3230", _("Woodsmoke"), _("Grey")],
        ["554545", _("Woody Brown"), _("Brown")],
        ["75876E", _("Xanadu"), _("Green")],
        ["FFFF00", _("Yellow"), _("Yellow")],
        ["9ACD32", _("Yellow Green"), _("Green")],
        ["73633E", _("Yellow Metal"), _("Yellow")],
        ["FFAE42", _("Yellow Orange"), _("Orange")],
        ["F49F35", _("Yellow Sea"), _("Yellow")],
        ["FFC5BB", _("Your Pink"), _("Red")],
        ["826A21", _("Yukon Gold"), _("Yellow")],
        ["C7B882", _("Yuma"), _("Yellow")],
        ["6B5A5A", _("Zambezi"), _("Brown")],
        ["B2C6B1", _("Zanah"), _("Green")],
        ["C6723B", _("Zest"), _("Orange")],
        ["3B3C38", _("Zeus"), _("Grey")],
        ["81A6AA", _("Ziggurat"), _("Blue")],
        ["EBC2AF", _("Zinnwaldite"), _("Brown")],
        ["DEE3E3", _("Zircon"), _("Grey")],
        ["DDC283", _("Zombie"), _("Yellow")],
        ["A29589", _("Zorba"), _("Brown")],
        ["17462E", _("Zuccini"), _("Green")],
        ["CDD5D5", _("Zumthor"), _("Grey")]
    ]

};

/* exported NameThatColor
 */
