#!/usr/bin/python3
# -*- coding: utf-8 -*-

import os
import sys

root_folder = os.path.realpath(os.path.abspath(os.path.join(
    os.path.normpath("{full_path_to_app_folder}"))))


if __name__ == "__main__":
    args = sys.argv[1:]
    os.chdir(root_folder)
    os.execv("%s/app.py" % root_folder, [" "] + args)
