%YAML 1.1
---
javascript_modules:
    - appletsUtils.js
    - customFileUtils.js
    - customTooltips.js
    - debugManager.js
    - globalConstants.js
    - globalUtils.js
python_modules:
    - xlets_settings
extra_files:
    - source: __app__/data/gschemas/debugManagerSchema.xml
      destination: schemas/org.cinnamon.{{XLET_TYPE}}s.{{UUID}}.gschema.xml
